- .travis.yml
* run tests with `{os:linux,go:{1.9,1.10}}` on every commit.
* run `{os:linux,go:master}`, `{os:osx,go:1.10}`, docker image nightly.
* ~10 min -> ~4 min
> ci: speedup build

- cmd/akashd/start_test.go
refs #124 
The flapping test may be caused because close is called while the database is initializing.
> attempt flapping test fix

- app/account/app.go
- app/provider/app.go
- cmd/akash/context/context.go
- cmd/akash/deployment.go
- cmd/akash/provider.go
- cmd/akash/query/account.go
- cmd/akash/query/deployment.go
- cmd/akash/query/lease.go
- cmd/akash/query/order.go
- cmd/akash/query/provider.go
- cmd/akash/query/query.go
- cmd/akash/send.go
- cmd/akashd/init.go
- keys/keys.go
- keys/parse.go
- query/client.go
- query/path.go
* query: re-usable object query moved from `cmd/akash/query`
* keys: parse more types
> query client, more key parsing

- cmd/akash/key.go
Fixes  #270 
Currently, the keys are retrieved using `akash key list` which is good for display but not optimized for scripting; for example to query the master account: 
```
$ akash query account $(akash key list  | grep master | awk '{print $2}')
```
This change add a simpler way to query for individual keys makes scripting experience better. The above command could be rewritten as follows:
```
$ akash query account $(akash key show master)
```
> cmd/akash: add key show

- glide.lock
- glide.yaml
- provider/cluster/kube/builder.go
The maximum allowed length for a domain name label is **63** bytes. The current implementation uses deployment ids which are **64** bytes long. 
For eg: `web.ece4d213af89da02c0f4b5e589dcb9dd9313d4fc228ba9ad316cc8fb79ac163a.147-75-71-243.aksh.io`
This patch uses UUIDs instead that are 36 bytes.
(fixes #324)
> provider: use uuid instead of deployment id for hostnames

- _docs/testnet/testnet-deployment.yml
There were too many apps in sjc and global presents a better picture
> docs: use global deployment for sample deployment

- glide.lock
- glide.yaml
Fixes a regression from Tendermint v0.30.0 which used the peer's SocketAddr to add the peer to the address book. This swallowed the peer's self-reported port which is important in case of reconnecting. It brings back NetAddress() to NodeInfo and uses it instead of SocketAddr for adding peers.
> tendermint: use v0.31.5

- _run/multi/Makefile
- _run/multi/akash-provider/run.sh
- _run/multi/akash-provider/templates/deployment.yaml
- _run/multi/akash-provider/values.yaml
- _run/multi/run.sh
- glide.lock
- glide.yaml
- provider/cluster/kube/builder.go
- provider/cluster/kube/config.go
Every service in the lease will be mapped to short uuid for example `yb4exzwaxnbvvr4cmavewa.kant.akashtest.net` when `AKASH_DEPLOYMENT_INGRESS_STATIC_HOST=true` and `AKASH_DEPLOYMENT_INGRESS_DOMAIN=kant.akashtest.net`
**Example Output:**
```
Deployment
==========
Deployment ID:        	9cc85023234af786a227f1a365f7b1d56a161d5614c971fd24abf6c740f2b56d
Deployment Groups(s): 	Group:        	global
Requirements:
Resources:    	Count:  	2
Price:  	100
CPU:    	250
Memory: 	134217728
Disk:   	1073741824
Fulfillment(s):       	Group:    	1
Price:    	15
Provider: 	90efa2ec8cb6aba9db9ee9bb9b119e41670f42903b9d5be61461509431a2aa45
Lease(s)
========
Lease ID:    	9cc85023234af786a227f1a365f7b1d56a161d5614c971fd24abf6c740f2b56d/1/2/90efa2ec8cb6aba9db9ee9bb9b119e41670f42903b9d5be61461509431a2aa45 …
```
> provider/cluster: add support for deployment ingress domains

- .goreleaser.yml
windows builds fails due to:
multiple-value "golang.org/x/sys/windows".GetCurrentProcess() in single-value context
> release: remove windows

- x/provider/types/errors.go
Fix for:
```
panic: error with code 2 is already registered: "invalid provider: not absoulte host uri"
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/errors.Register(0x4c4db8d, 0x8, 0x2, 0x4c6d951, 0x23, 0xc000f7d710)
/Users/gosuri/code/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.0/types/errors/errors.go:101 +0x389
github.com/ovrclk/akash/x/provider/types.init()
/Users/gosuri/code/go/src/github.com/ovrclk/akash/x/provider/types/errors.go:14 +0x112
```
> fix: panic: error with code 2 is already registered: "invalid provider: not absoulte host uri"

- .buildkite/script/test.sh
- Makefile
Unknown history of these test requirements, however currently tests are
failing due to missing the _build/akash[d] binaries.
This change adds the Make `image-bins` step to all of the targets which
run tests. Locally this has corrected the reproduced test failures we're
seeing on BuildKite.
> Update Makefile dependencies

- .github/workflows/tests.yml
* `lint all` step that runs everything and always exits cleanly.
* individual steps for linters that need to be addressed.
fixes #537
> ci: fix golangci-lint

- .goreleaser.yml
This change updates to filename to `Dockerfile.akashctl`
declaration which matches our new naming convention. Hopefully fixing
the broken Goreleaser pipeline step.
> fix: Goreleaser referenced old Dockerfile.akash

- provider/cluster/client.go
- provider/cluster/inventory.go
- provider/cluster/kube/client.go
- provider/cluster/kube/deployment_test.go
- provider/cluster/manager.go
- provider/cluster/monitor.go
- provider/cluster/service.go
Kube provider client now accepts contexts
Removed struct-stored context.Context from k8s client{}. Now all functions
accept the caller's Context to manage shutdown behavior.
fixes #555
Signed-off-by: Joshua Roppo <joshroppo@gmail.com>
> refactor: Client interface accepts Context params

- .github/workflows/tests.yml
- provider/cluster/kube/builder.go
- provider/cluster/kube/builder_test.go
- x/market/types/id.go
The usage of sha1 was removed and updated to sha256. The use of `sha*`
is minor compared to the changes which fix the functionality of creating
unique k8s object names based on the LeaseID.
Added test to assert that the name is properly passed into the k8s
type.
fixes #550
> fix: updated code using unsafe package

- .github/workflows/tests.yml
- provider/bidengine/service.go
- provider/cluster/inventory.go
- provider/cluster/kube/builder.go
- provider/manifest/handler.go
- provider/manifest/manager.go
- x/deployment/client/cli/tx.go
- x/deployment/handler/handler.go
- x/deployment/query/querier.go
- x/market/client/cli/tx.go
- x/market/query/querier.go
- x/provider/client/cli/tx.go
- x/provider/query/querier.go
'_'ing function parameters which are not used, updating some CLI
commands to use their 'key' parameters to enhance Cobra descriptions, no
changes to interfaces or function calls.
Used `// nolint` to silence all lint violations which were caused by
functions returning values which were zero-value or errors that were
always nil. Fixing would require chaning methods which might need to be
changed back later.
fixes #547
> lint: unparam cleanup of unused varaibles

- sdkutil/event.go
- x/deployment/types/event.go
- x/deployment/types/events_test.go
- x/market/types/event.go
* Previously used the sdk.EventTypeMessage == "message" string to
identify all of our messages. This provided little value.
* Updated all ephemeral messages to be prefixed with
"sdkutil.EventTypeMessage" == "akash.v1".
* Added tests to assert successful event parsing, though they just check 
there are no parsing errors right now.
fixes #607
> refactor: replaces events type const

- events/publish.go
- events/query.go
- provider/cmd/run.go
* Deactivated events.Publish subscribes to the tendermint event bus
and re-published events to the rest of the provider/
modules.
* Small docstring additions.
fixes #606
> perf: remove provider transaction event subscription

- app/app.go
> Fix subspace already occupied error

- testutil/ids.go
- x/market/handler/endblock.go
- x/market/handler/endblock_test.go
Deterministically choose a winner from a set of bids for an order.
* Sort bids on order: collect lowest with matching bid values
* From lowest bids, aggregate all bids' strings and fnv hash
* `fnv value` %(remainder) len(matching bids) = winning bid.
* Unit tests to assert deterministic return values.
* TODO: https://github.com/ovrclk/akash/issues/637 to improve 
bid query performance.
fixes #619
> enhancement: equivalent bids deterministic winner

- validation/pricing.go
prevents panic if Price is initialized with `sdk.Coin{}`
> fix: check price object is valid

- integration/deployment_test.go
- integration/market_test.go
- integration/test_helpers.go
- x/deployment/query/path.go
- x/deployment/query/types.go
- x/deployment/types/id.go
- x/deployment/types/msgs.go
- x/market/query/path.go
- x/market/query/types.go
- x/market/types/id.go
- x/market/types/msgs.go
- x/provider/types/msgs.go
> Improve validation of address with VerifyAddressFormat

- x/market/handler/handler.go
- x/market/handler/handler_test.go
> Allow to close bid when bid state is open

- validation/config.go
if total amount of memory in group less then 1G
calculatePriceRange will always return range 0..1.
fixes #640 ?
> fix: adjust MaxGroupMemPrice

- x/market/types/errors.go
- x/market/types/types.go
fixes #702
result
```
{
"height": "301",
"txhash": "5690F8A18FA254243D94B466ABAABF7437D80FA8EE43E71008596BF2CE9E527C",
"codespace": "market",
"code": 20,
"raw_log": "order closed: failed to execute message; message index: 0",
"gas_wanted": "200000",
"gas_used": "36491"
}
```
> fix: declare market bid errors as sdkerror

- testutil/base.go
- testutil/deployment.go
- x/deployment/handler/endblock.go
- x/deployment/handler/endblock_test.go
- x/deployment/keeper/keeper.go
- x/deployment/keeper/keeper_test.go
- x/market/handler/handler_test.go
* WithDeploymentsActive() added to do basic filtering of all
deployments which are in active state.
* Used in Deployment's EndBlock function.
* Tests on EndBlock attempting to assert expected behavior.
* TODO: Assert EndBlock error cases.
* testutil.CoinDenom added to enable passing created coins into testutil
methods which accept sdk.Coin's with consistent denoms.
* Updated all tests which fit this case.
related: #604
> Deployment EndBlock testing(prep for Indexing)

- Makefile
- app/params/weights.go
- events/publish_test.go
- x/deployment/client/cli/tx.go
- x/deployment/handler/handler.go
- x/deployment/keeper/keeper.go
- x/deployment/keeper/keeper_test.go
- x/deployment/simulation/operations.go
- x/deployment/types/codec.go
- x/deployment/types/errors.go
- x/deployment/types/event.go
- x/deployment/types/events_test.go
- x/deployment/types/msgs.go
- x/deployment/types/types.go
- x/deployment/types/types_test.go
Enable closing a specific group within an existing Akash Deployment.
This will signal the provider to set the Group.State to Closed.
`akashctl tx deployment group close --owner=? --dseq=? --gseq=?` command
added to send the `MsgCloseGroup`.
Simulation tests passing: With a prequisite in SimulateMsgCloseGroup() to skip
sending the MsgGroupClose if the Group.State is already Closed. This is
not the same behavior as the Deployment's Simulation function, but
Simulate...Group throws the handleMsgCloseGroup() ErrGroupClosed when
the simulation runs.
fixes: #642
> feat: Close Group Message functionality

- x/provider/handler/handler.go
- x/provider/handler/handler_test.go
- x/provider/types/errors.go
- x/provider/types/types.go
> fix: reject provider messages with duplicated attributes

- x/deployment/handler/endblock.go
- x/deployment/handler/endblock_test.go
- x/deployment/keeper/keeper.go
- x/deployment/keeper/keeper_test.go
- x/deployment/keeper/key.go
- x/deployment/keeper/key_test.go
To improve the performance of the `deployment` module's EndBlock method.
This PR creates a second prefix key in `x/deployment/keeper` to
facilitate tracking the newly created Group's in the 0x03 prefix.
This change short circuits the need for tracking Active Deployments
which @boz identified on the [prior
PR](https://github.com/ovrclk/akash/pull/723#pullrequestreview-441824680).
Tests indicate things are working correctly. However that's one area I'd
like which could probably use more development/abuse.
refs: #604
> feat: 604 Open Groups Index

- x/deployment/keeper/key.go
- x/market/handler/endblock.go
- x/market/keeper/keeper.go
- x/market/keeper/keeper_test.go
- x/market/keeper/key.go
- x/market/keeper/key_test.go
Equivalent to the [Open Group indexing](https://github.com/ovrclk/akash/pull/729) queries.
Creates a second index in the `market` module which does not store data,
only tracks active Leases. Once a lease is moved out of active state the
key is removed from the index.
Testing improvement is not significant, mostly depending on existing
tests. More will come down with the Open Bids index.
refs: #604
> feat:604 Active Lease indexing

- sdkutil/event.go
- sdkutil/object_id.go
- sdkutil/object_id_test.go
- sdkutil/query.go
- testutil/base.go
- x/deployment/types/id.go
- x/market/types/id.go
- x/provider/handler/handler.go
Provide pretty printer for Block address types with AccAddress, DSeq,
GSeq, and OSeq fields which will be printed to logs and command
responses.
`sdkutil` package provides helper methods to format and parse values
from the human readable format.
```
Format: [Owner AccAddress]/[DSeq]/[GSeq]/[OSeq]/[Provider AccAddress]
eg: akash1vgv30hr8lel8r7270wywmak5c82es3njws3u4z/795423625/1/1/akash1pxqksfr60zc6uadht6300uavwl3s58ct0apt9w
```
fixes: #727
> feat:727 Friendly stringer of Block ID types

- events/publish_test.go
- integration/deployment_test.go
- integration/test_helpers.go
- sdl/sdl.go
- sdl/v1.go
- sdl/v1_test.go
- testutil/deployment.go
- testutil/ids.go
- x/deployment/client/cli/tx.go
- x/deployment/client/cli/util.go
- x/deployment/handler/handler.go
- x/deployment/handler/handler_test.go
- x/deployment/keeper/keeper.go
- x/deployment/simulation/operations.go
- x/deployment/testdata/deployment-v2.yaml
- x/deployment/types/event.go
- x/deployment/types/events_test.go
- x/deployment/types/msgs.go
- x/deployment/types/types_test.go
Implementation of passing a Deployment manifest's Version from Create and Update commands and messages.
* `sdl.VersionSha` package produces deterministic version hash from SDL struct.
* `akashctl tx deployment [create|update]` generates and sets Version field.
* `testutil` package updated to provide a consistent Deployment.Version value.
* `testutil.DeploymentVersion()` provides random version sums.
* Assertions/test that the Version is passed to the keeper via
`MsgUpdateDeployment` & `MsgCreateDeployment`.
* MsgUpdateDeployment passes GroupSpec to update image tags
* Test integration tests for `deployment update`.
* New deployment-v2.yaml with tag change.
* Assert's Version field is changed post update.
* Tests to validate different deployment Versions
* Compare differing deployment yaml …
> feat:565 Deployment Version Field

- sdkutil/object_id.go
- sdkutil/object_id_test.go
Improved testing around formatting *ID types to their string
representation, and parsing string data back into original type.
(consume generated dog food)
Tests now run full circle from BlockID.String(), and reflected
BlockID.String() matches the original IDs.String().
fixes: #752
Played around with default `%s` formatting of data types; eg `types.Deployment`. As is currently an reference to the wrapping type of an *ID type, will return the stringer of the ID type, which at least does provide clarity into what ID is being referenced. It would be nice to come up with a consistent String() convention for types with `state`, version, prices.
> fix:752 Stringer Test Assertions

- _run/common-commands.mk
- _run/kube/README.md
- _run/single/README.md
- client/client.go
- provider/cluster/service.go
- provider/event/events.go
- provider/manifest/manager.go
- provider/manifest/service.go
- sdl/sdl.go
- validation/manifest.go
* ~~Performance improvements to Active Lease lookup~~
* Code Documentation in the `provider` codebase
* Validation of manifest version to blockchain Deployment version
* Asserts that manifest object provided is correct.
* ManifestVersion() method to extract Version from Manifest type.
* Makefile `deployment-update` command added
* Document Deployment update and (re)sending manifest.
fixes: #762
> feat:762 Deployment Version Updating validation

- .github/workflows/k8s-integration.yaml
- Makefile
- _run/common-kind.mk
- integration/cosmostests/LICENSE
- integration/cosmostests/gobash.go
- integration/cosmostests/process.go
- integration/deployment_test.go
- integration/e2e_test.go
- integration/market_test.go
- integration/test_helpers.go
- provider/cluster/kube/client.go
Functional integration test of the Provider running against a KinD cluster locally or in GH Actions. Uses previous `integration` test functionality of bootstraping a blockchain, data, keys, and runs an Akash node. A KinD k8s cluster is created, and a `provider` service is connected to it and run.
A tenant creates a Akash demo-app Deployment, and sends the manifest to Provider. The Provider manages the deployment and runs it in KinD. The integration test then requests the static web page from the k8s external IP:Port and validates that the App is running.
fixes: #777
> feat: E2E provider integration test

- _docs/examples/provider/README.md
- _docs/examples/provider/kustomization.yaml
Documentation to provide more context for configuration parameters to
create a Provider.
* `DOMAIN_INGRESS` envvar caused some issues with the test cluster which
traced back to this configuration of the Provider Deployment.
* Required updating Cloudflare DNS as well.
* Tiny typo fixed in kustomize template.
* `kustomize` added to README required tool list.
> K8s Provider Documentation update

- README.md
- _docs/examples/provider/README.md
- _docs/kustomize/README.md
- _docs/kustomize/akash-provider/kustomization.yaml
- _docs/kustomize/akash-provider/rbac.yaml
- _docs/kustomize/akash-services/kustomization.yaml
- _docs/kustomize/akash-services/network-policies.yaml
- _docs/kustomize/akashd/kustomization.yaml
- _docs/kustomize/networking/namespace.yaml
- _docs/kustomize/networking/network-policy-default-ns-deny.yaml
- _run/common-kind.mk
- _run/kube/README.md
- _run/single/Makefile
- _run/single/README.md
- _run/single/kind-config-calico.yaml
- _run/single/kustomize/akash-provider/kustomization.yaml
- _run/single/kustomize/akashd/kustomization.yaml
- script/setup-kind.sh
* Calico up and running inside of _run/single KinD
* Configuration to utilize Calico as network manager.
* Updated Makefile targets adding `kind-cluster-calico-create`
* `akash-services` Namespace Defined for Akash services
* Requires Namespace to be created as preflight to Calico launch.
* Network policies enforce denying ingress traffic to `akash-services`
namespace except from system and ingress namespaces.(protect from
tenant mischief)
* Kustomize templates for Akashd & Provider updated to use Namespace.
> Base Network Policies for Akash Services

- _run/single/Makefile
- _run/single/kustomize/akashd/kustomization.yaml
* Makefile script missing KEY_OPT arguments
* Kustomize needed to be updated to reference new binary name.
Work to get #794 back up and running.
fixes: #808 (hopefully)
> 808 fixes to _run/single

- .goreleaser.yaml
Debugging problems with #808 tags not getting built. Plausibly due to
whitespace breaking the map of arguments in YAML preparsing.
related: #794
> Goreleaser whitespace eradication

- Makefile
> fix: modvendor not copying cosmos-sdk .proto files

- _build/Dockerfile.akash
- make/mod.mk
- make/releasing.mk
Changes
1. Fix a typo, I think you meant `mod tidy` not `mod tid` here
2. Switch to Golang as base image to fix issue around dynamic libraries like `librt`. Tried alpine but Go binaries on alpine have other issues. My locally built container can run the `akash` binary after this change.
3. Pass the `-f` command to all the invocations of the golang-cross container. Not 100% sure on this one but `release-dry-run` was failing for me.
> Fix buildfile issues around Docker, switch to Golang base image

- _docs/kustomize/akash-provider/deployment.yaml
- _docs/kustomize/akash-provider/ingress.yaml
- _docs/kustomize/akash-provider/run.sh
- _docs/kustomize/akashd/ingress.yaml
- _docs/kustomize/akashd/run.sh
- _docs/kustomize/akashd/service.yaml
- _run/common-kind.mk
- _run/kube/deployment.yaml
- _run/single/Makefile
- _run/single/README.md
- _run/single/kustomize/akash-provider/.gitignore
- _run/single/kustomize/akash-provider/kustomization.yaml
- _run/single/kustomize/akashd/.gitignore
- _run/single/kustomize/akashd/kustomization.yaml
This is a bunch of changes I've made to get the example `single` working. I have it working with my custom hacked up docker image, once Cosmos SDK merges my fix it should be possible to have a working example again.
This is a brief summary of the changes
1. Fix things referencing `akashctl` & `AKASH_CTL` since those are obsolete
2. Update the `run.sh` scripts that are part of kustomize to set the correct flags
3. Add the ping command to the Makefile for this example
4. Allow uploading a custom image via Makefile commands
5. Remove some un-needed verbs in the Makefile
6. Update the Ingress declarations to be v1
> Fix kustomize in the 'single' example #838

- provider/cluster/kube/apply.go
- provider/cluster/kube/builder.go
- provider/cluster/kube/builder_test.go
- provider/cluster/kube/client.go
- provider/cluster/kube/k8s_integration_test.go
* Used Kubernetes 'restrictive' pod security policy as default for now. Ideally we'll make this a 
* Main change: No running as root in various configured setups.
* No privilege escalation allowed by k8s.
* Applied to all namespaces created for tenants by the `manifestBuilder` type.
* This should be tuned by SDL settings
* Passes integration testing.
* Update to tests to match namespace names for tests. The previously
created Namespace isn't used by downstream builders, which is a bit confusing and needs more debugging.
> Restrictive K8s PodSecurityPolicy applied to tenant namespaces

- Makefile
Setting the variables using 'export' causes them to execute the shell
commands for *every* make command. They are only useful for `kind` make
targets, so the error messages from their run in all other instances
produces a lot of irrelevant error log messages.
eg:
```
$make test-sublinters
docker run --rm -v github.com/ovrclk/akash:/workspace -w /workspace golangci/golangci-lint:v1.31.0-alpine golangci-lint run ./... --disable-all --deadline=5m --enable deadcode
Error: No such container: kube-control-plane
Error: No such container: kube-control-plane
docker run --rm -v /home/ropes/go/src/github.com/ovrclk/akash:/workspace -w /workspace golangci/golangci-lint:v1.31.0-alpine golangci-lint run ./... --disable-all --deadline=5m --enable misspell --no-config
Error: No such container: …
```
> fix: exported Makefile variables caused noise

- .github/workflows/release.yaml
Attempt to fix the `release` GH action which is
[currently](https://github.com/ovrclk/akash/runs/1281859108?check_suite_focus=true) resulting in
an error:
```
Run echo ::set-output name=MAINNET::$([[ $(./script/semver.sh get minor ${GITHUB_REF#refs/tags/) % 2 ]] && echo true || echo false)
/home/runner/work/_temp/41120ada-b8f4-460f-b416-db488976ea0b.sh: line 1: unexpected EOF while looking for matching `}'
Error: Process completed with exit code 2.
```
Fix: remove unbalanced and unnecessary `{`
[GH Documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables) indicates no curly braces are needed.
> fix: GH release syntax

- Makefile
fixes issue with goreleaser not passing link flag
causing akash version to return empty string
> ci: remove single quotes wrap from GORELEASER_LD_FLAGS

- provider/cluster/kube/builder.go
An incorrect Network Policy namespace selector for Nginx's Ingress
controller was blocking connections. This small fix corrects the
selector allowing traffic to pass through Ingress.
fixes: #911
> Network Policy corrected for Ingress-Nginx

- provider/bidengine/order.go
- provider/bidengine/order_test.go
- testutil/channel_wait.go
I think in the process of fixing one race, I introduced another one. This refactor should fix that. I also made some changes suggested by @troian  to prevent non obvious timeouts in CI.
> test(provider): fix race in test

- provider/cluster/kube/builder.go
- x/deployment/types/validation_config.go
This bumps up the limit & enforces it on kubernetes containers. There is no such feature as a storage limit, only ephemeral storage limits. We don't create actual kubernetes storage that I see anywhere.
> feat(provider): Set limits when configuring containers in kubernetes

- provider/bidengine/order.go
- provider/cluster/inventory.go
- provider/cluster/mocks/cluster.go
- provider/cluster/service.go
Unreserve resources for leases that don't have yet
have a manager (manifest not received).
* always remove all resources for an order
* change signature to no longer return removed resources
> fix(inventory): unreserve unmanaged orders

- .github/workflows/release.yaml
- make/releasing.mk
goreleaser with --skip-validate=false fails
if head commit is not same ref as a tag
--snaphot fixed it, as these builds are actually snapshots
> ci: fix ci build when running on branches

- client/broadcaster/serial.go
- provider/cluster/service.go
- provider/cmd/leaseStatus.go
- provider/cmd/manifest.go
- provider/cmd/root.go
- provider/cmd/run.go
- provider/cmd/serviceLogs.go
- provider/cmd/serviceStatus.go
- provider/cmd/status.go
- provider/gateway/client.go
- provider/gateway/router.go
- provider/gateway/router_test.go
- provider/manifest/service.go
- validation/manifest.go
- validation/manifest_validation_errors.go
Changes
1. Suppress showing the usage when we have an internal failure (like 404 from the remote). Still shows up if the user does a `help`command
2. Refactor the way the gateway router handles errors & check for all the special cases I could find
3. Add tests around the gateway router
4. Refactor the way the provider client handles errors from the remote. They get returned to cobra, but beforehand the actual HTTP body is captured and displayed to the user. This should contain useful information from the provider i.e. `send-manifest` fails due to an invalid manifest.
5. Fix some errors that I think came in from master?
6. Rename `ensureManger` to `ensureManager` !
> Cleanup provider error response handling

- cmd/common/util.go
- cmd/common/util_test.go
- events/cmd/root.go
- integration/e2e_test.go
- provider/cluster/kube/client.go
- provider/cmd/leaseStatus.go
- provider/cmd/serviceLogs.go
- provider/cmd/serviceStatus.go
- provider/cmd/status.go
- provider/cmd/test_helpers.go
- x/market/client/cli/lease.go
Changes
1. Add provider e2e tests
2. Fix some issues I found around service-status & lease-status having missing data
3. Refactor the common function I had to use the cosmos SDK context so the tests can capture
the output & test against it
> Add provider e2e tests

- provider/cluster/kube/builder.go
- provider/cluster/kube/deployment_test.go
This just adds in the deployment information for the running containers. Not required but can be useful in some circumstances.
> feat(provider): Add deployment information to running containers

- Makefile
- README_e2e.md
- integration/test_helpers.go
- make/test-integration.mk
I have a companion PR here https://github.com/ovrclk/kubespray/pull/3
When both of these are put together it does the following
1. Gives up the ability to provision a single master K8S cluster in Vagrant
2. Configures the cluster using our example
3. Gives us a way to automatically run the e2e tests against the K8S cluster
The K8S cluster is a single master with two other nodes. I'm running it in VirtualBox, you need about 6 GB of free memory for this to work. Theoretically we can point Vagrant at a VMWare cluster or AWS if we want to run e2e tests against a huge cluster for some reason.
The main drawback here is we can't run this automatically inside of Github CI.
Once this is merged we need to work on adding more e2e tests as there is substantially more we can cover in those tests.
> Allow testing via K8S running in vagrant

- validation/manifest.go
- validation/manifest_test.go
This makes the service names have to be valid hostnames
> fix(provider): Require service names to confirm to DNS-1123 standard

- provider/cluster/config.go
- provider/cluster/inventory.go
- provider/cluster/kube/builder.go
- provider/cluster/kube/client.go
- provider/cluster/kube/client_test.go
- provider/cluster/kube/settings.go
- provider/cluster/manager.go
- provider/cluster/monitor.go
- provider/cluster/util/util.go
- provider/cluster/util/util_test.go
- provider/cmd/run.go
- provider/config.go
- provider/service.go
- script/setup-kind.sh
The main issue I found while testing things using my local kubernetes cluster is that the provider continues to bid on things even after the available resources are consumed in the cluster. The provider was setting a limit only in the container pods (which also becomes the request in that case). Kubernetes enforces this, refusing to spinup new pods if available resources aren't there. The provider was continuing to bid because the "inventory" was determined by getting values from the metrics server. For almost all deployment, utilized CPU is less than the CPU limit enforced in the kubernetes pod. It's been changed to just measure the commit CPU by going through all the pods in the cluster.
After this changes, the provider just stops bidding once the available CPU is no longer enough to …
> feat(provider): Add basic resource overcommit in the kubernetes cluster

- validation/manifest.go
- validation/manifest_test.go
If an environmental variable name is invalid, this code change causes the SDL to fail validation.
> fix(provider): Reject SDL describing invalid env. var. names

- _docs/kustomize/networking/namespace.yaml
- _docs/provider/kube/ns-network-policies.yaml
- integration/e2e_test.go
- integration/test_helpers.go
- make/test-integration.mk
- provider/cluster/kube/apply.go
- provider/cluster/kube/builder.go
- provider/cluster/kube/builder_test.go
- provider/cmd/run.go
- x/deployment/testdata/deployment-v2-c2c.yaml
- x/deployment/testdata/deployment-v2-nodeport.yaml
This should have the following changes
1. Create a default network policy **within each deployment namespace**, that applies to all pods
2. Enable access from Ingress controller to pod containers by default
3. Enable DNS access from pod containers by default
4. Allow public IPV4 addresses to be accesed from pod containers, but deny private IPV4 addresses
5. Explicitly allow connections between pods within the same namespace
6. For each service with a nodeport, add a policy **selecting just that pod** to open the appropriate port & protocol
The following tests are added
1. End to end test of NodePort connectivity - possible when you're testing against K8S in Vagrant
2. End to end test of container to container communication in the same deployment. I'm using Redis & webdis for this.
These …
> fix(provider): Update network policies for deployments

- integration/e2e_test.go
- integration/test_helpers.go
- provider/cluster/config.go
- provider/cluster/hostname.go
- provider/cluster/hostname_test.go
- provider/cluster/manager.go
- provider/cluster/service.go
- provider/cluster/util/util.go
- provider/cmd/run.go
- provider/config.go
- provider/manifest/config.go
- provider/manifest/manager.go
- provider/manifest/manager_test.go
- provider/manifest/service.go
- provider/service.go
- x/deployment/testdata/deployment-v2-newcontainer.yaml
- x/deployment/testdata/deployment-v2-nohost.yaml
- x/deployment/testdata/deployment-v2-updateA.yaml
- x/deployment/testdata/deployment-v2-updateB.yaml
In this pull request I did the following
1. If "DeploymentIngressStaticHosts" is set, we require all deployment groups to have at least on hostname specified
if they are going to be used for HTTP via a Kubernetes Ingress. No restrictions are added to node port stuff.
2. Checked to see if hostnames are in use before accepting a manifest. If it is in use, reject the manifest
3. Add an option to block a hostname or domains. Hostnames can be specified by using a string like "bobsdefi.com". An entire
domain can be blocked by using a string like ".bobsdefi.com". This is specified a string slice in the code, and the command line option
can be given multiple times to add multiple entries.
Implementation notes:
1. I added something as part of `provider/cluster` that I am calling the hostname …
> feat(provider): Validate hostnames as part of a manifest before accepting it

- _run/common.mk
The `_run/kube` examples and similar are broken.
It looks like the `gentx` command no longer actually wants the `--amount` flag, despite it being listed as a flag. When you specify it as a command line argument instead of a flag it works.
> fix(examples): The amount in gentx is no longer a command line switch

- Makefile
For some reason when running commands like `make test-sublinters` it is equivalent to unplugging & plugging in the network cable on the host each time docker is run.
This disables the network access for the linters run in docker, which don't need it anyways.
> fix(lint): Disable network when running the linters

- sdl/coin.go
- sdl/coin_test.go
Apparently all the Cosmos coin parsing code just truncates any decimal values.
I just changed our parsing code to check for a fractional value beforehand and reject it at that point.
> fix(sdl): Reject decimal coin values

- cmd/akash/cmd/root.go
- deploy/cmd/create.go
- deploy/cmd/deployment-data.go
- deploy/cmd/event-emitters.go
- deploy/cmd/event-handlers.go
- deploy/cmd/root.go
- deploy/cmd/utils.go
- go.mod
- go.sum
- provider/cluster/hostname.go
- provider/cluster/monitor.go
- provider/gateway/rest/client.go
- provider/service.go
- x/cert/client/cli/tx.go
- x/deployment/client/cli/tx.go
- x/deployment/client/cli/util.go
I made the following changes from the work that @anilCSE started
1. If we get a deployment closed event, just bail
2. If we get a lease closed event, just bail
3. Don't return the error for context cancelled if all leases are reporting as OK by providers
4. Run service status after all leases are up and dump the result to standard out.
5. Don't log the same service status multiple times
6. Use a context with a deadline, tie everything to that. Poll "forever" or until the deadline is reached
> feat(provider): Add the deploy tool

- provider/bidengine/order_test.go
fixes #1040
removed scaffold.cluster.AssertNotCalled as
Unreserve event may arrive before code reaches order.lc.Done()
> test(bidengine): fix flapping order test

- .gitignore
- Makefile
- docgen/main.go
- make/releasing.mk
This adds an executable that dumps the markdown documentation for the `akash` command into whatever destination pass on the command line.
> feat(docs): Add executable for generating Markdown documentation

- .github/workflows/release.yaml
GOLANG_CROSS_VERSION is immutable in makefile
> ci(release): use GOLANG_VERSION to configure GOLANG_CROSS_VERSION

- .github/workflows/release.yaml
> ci(go): remove v prefix from go version

- provider/cluster/kube/client.go
I couldn't find any docs on this, but switching this over should result in the client always making the request immediately rather than throttling at the application level.
> fix(provider): disable kubernetes client API rate limiting

- deploy/cmd/event-handlers.go
Just skip an unknown event, it should be no problem at all.
> fix(deploy tool): Do not crash on unknown events

- provider/cluster/kube/client.go
- provider/cluster/kube/client_test.go
- provider/cluster/monitor.go
- provider/manifest/manager.go
What I changed here
1. Some better error messages in the logs
2. For service status, pull the manifest from the CRD in kubernetes
3. Only check the ingress status if CRD says the service should have an ingress object
4. Add some tests using mocks
> fix(provider): don't try and get ingress data for a service that has none 

- go.mod
- go.sum
this switches over to our temporary forks of Cosmos & Tendermint to get the following changes
1. The address prefix fix backported into Cosmos SDK
2. Prevent dropping of events if the channel is full in Tendermint
3. Enable Websocket Ping Pong behavior by default in Tendermint
> fix: Switch to versions of Cosmos & Tendermint with backports & patches

- provider/cluster/kube/client.go
- provider/cluster/types/types.go
- provider/gateway/rest/router.go
fixes #1124
add missed defer statement
add Note field describing event details
**tested with SDL**
```yaml
---
version: "2.0"
services:
web:
image: polinux/stress
command:
- "stress"
args:
- "--vm"
- "1"
- "--vm-bytes"
- "250M"
- "--vm-hang"
- "1"
expose:
- port: 80
as: 80
accept:
- hello.localhost
to:
- global: true
profiles:
compute:
web:
resources:
cpu:
units: 0.1
memory:
size: 100Mi
storage:
size: 128Mi
placement:
westcoast:
attributes:
region: us-west
pricing:
web:
denom: uakt
amount: 1000
deployment:
web:
westcoast:
profile: web
count: 1
```
**output example**
```json
{
"type": "Warning",
"time": "0001-01-01T00:00:00Z",
"reason": "Failed",
"note": "Error: failed to create containerd task: OCI runtime create failed: …
```
> fix(provider): not showing all events

- .github/workflows/macos.yaml
containers not supported in macos env of github actions
> ci(macos): load build env using bash

- cmd/akash/cmd/root.go
fixes #1150
fixing issue when status command prints output to stderr
> fix(cli): set out/err streams to be stdout/stderr respectively

- provider/balance_checker.go
Just remove this log statement for now, it's a debug level anyways. We shouldn't be dependent on it.
> fix(provider): Remove a race condition around the logger

- provider/balance_checker_test.go
- x/audit/client/cli/query.go
- x/audit/client/cli/tx.go
- x/cert/client/cli/query.go
- x/cert/client/cli/tx.go
- x/deployment/client/cli/query.go
- x/deployment/client/cli/tx.go
- x/market/client/cli/query.go
- x/market/client/cli/tx.go
- x/provider/client/cli/query.go
- x/provider/client/cli/tx.go
I don't know why we had this turned off, but I did a smoke test and it fixed the issue for me where it was trying to parse the home directory that is stored at `~/.akash`. I don't see any reason to have this disabled.
> fix: parse CLI flags for all commands

- events/publish.go
- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/bidengine/provider_attributes.go
- provider/bidengine/provider_attributes_test.go
- provider/bidengine/service.go
- x/audit/keeper/keeper.go
- x/audit/types/event.go
I think I made this way more complex than it needed to be, but it seems that everything is working as it should now. The provider only bids on deployments if has those attributes & the correct signature  is on the blockchain.
> fix(provider): only bid on deployments that attributes have been audited

- .github/workflows/k8s-integration.yaml
- .github/workflows/macos.yaml
- .github/workflows/release.yaml
- .github/workflows/sims.yaml
- .github/workflows/tests.yaml
it turns out that `^` means `min version` not `exact version`
> ci(setup-go): remove ^ to exact match go version

- x/market/client/cli/tx.go
The CLI spits out the wrong description for the `withdraw` command
> fix(cli): Update the description of the withdraw command

- sdkutil/broadcast.go
- x/audit/client/cli/tx.go
- x/cert/client/cli/tx.go
- x/deployment/client/cli/tx.go
- x/market/client/cli/tx.go
- x/provider/client/cli/tx.go
Rewrite of https://github.com/cosmos/cosmos-sdk/blob/ca98fda6eae597b1e7d468f96d030b6d905748d7/client/tx/tx.go#L29
with a different method for broadcast-mode=block:
1. use BroadcastSync
2. query for the tx until timeout or the tx is found in a block.
> feat(sdkutil): retry in broadcast-mode block

- provider/bidengine/config.go
- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/cmd/run.go
- provider/config.go
- provider/service.go
After a bid is created, just start a timer. If the timer is reached, cancel the bid and unreserve capacity.
This prevents a bunch of bids from taking up all capacity without any actual use of it.
> feat(provider): cancel bids if no lease is created

- provider/cluster/service.go
- provider/cmd/run.go
- provider/config.go
- provider/manifest/config.go
- provider/manifest/service.go
- provider/manifest/watchdog.go
- provider/manifest/watchdog_test.go
- provider/service.go
This starts a watchdog per deployment ID that either is:
1. Cancelled when a manifest arrives 
2. Closes the bid when a timeout is reached
This should save AKT of folks who for someone can't send a valid manifest to the provider
> Cancel bid if a manifest is not received

- .github/workflows/proto.yaml
required by make modvendor target
> ci(proto): setup go environment for proto

- provider/cmd/helpers.go
- provider/cmd/leaseLogs.go
- provider/cmd/manifest.go
- provider/cmd/serviceStatus.go
fixes #1177
output examples
**text**
```text
provider: akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7
status: PASS
provider: akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal
status: PASS
```
**yaml**
```yaml
- provider: akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7
status: PASS
- provider: akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal
status: PASS
```
**json**
```json
[{
"provider": "akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7",
"status": "PASS"
}, {
"provider": "akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal",
"status": "PASS"
}]
```
> fix(provider): query provider if flag is not supplied for send-manifest

- go.mod
- provider/bidengine/order.go
- provider/bidengine/service.go
- provider/cluster/client.go
- provider/cluster/inventory.go
- provider/cluster/inventory_test.go
- provider/cluster/kube/apply.go
- provider/cluster/kube/client.go
- provider/cluster/lease_withdraw.go
- provider/cluster/manager.go
- provider/cluster/monitor.go
- provider/cluster/service.go
- provider/cluster/types/types.go
- provider/cmd/metrics.go
- provider/cmd/run.go
- provider/manifest/service.go
- util/metrics/metrics.go
This adds a bunch of metrics around critical stuff. To enable it on the provider you just pass a command like arg like `--metrics-listener 0.0.0.0:3331` and it starts. If not specified, it doesn't start the metrics listener
> Add prometheus metrics to provider

- _run/kube/README.md
- provider/cmd/helpers.go
- provider/cmd/leaseEvents.go
- provider/cmd/leaseLogs.go
- provider/cmd/manifest.go
fixes #1250
lease events example
```json
{
"type": "Warning",
"time": "0001-01-01T00:00:00Z",
"reason": "Failed",
"note": "Error: ImagePullBackOff",
"object": {
"kind": "Pod",
"namespace": "4a7d0egn6o6n277feui0o8457nvr4gt6k3qjvjm0qsdi0",
"name": "web-7654dc49f7-5mhv6"
},
"lease_id": {
"owner": "akash1zlqr03j0mk04guz9k9t8p0w4tvdqxyzkz2d0pw",
"dseq": 1,
"gseq": 1,
"oseq": 1,
"provider": "akash1lxl3a62vn0rkzxacyz4zky679jmcwl3n2eqgcw"
}
}
```
log output as json
```json
{
"name": "web-68d66d985b-k426m",
"message": "2021-05-13T07:00:59+0000 ERROR An error is usually an exception that has been caught and not handled.",
"lease_id": {
"owner": "akash1zlqr03j0mk04guz9k9t8p0w4tvdqxyzkz2d0pw",
"dseq": 2,
"gseq": 1,
"oseq": 1,
"provider": "akash1lxl3a62vn0rkzxacyz4zky679jmcwl3n2eqgcw"
}
}
```
log …
> refactor(provider/cli): show logs/events for all leases by default

- provider/bidengine/service.go
- provider/cluster/lease_withdraw.go
- provider/cluster/manager.go
- provider/manifest/manager.go
- provider/manifest/service.go
We were running out of memory in prod.
Using the pprof package I could see the number of goroutines in pubsub code kept going up. Also a bunch of them sitting on `WatchChannel` in the `go-lifecycle` package
I changed the following.
1. Make sure we call `.Close()` on all pubsub subscribers
2. Remove a pubsub subscriber we aren't using
3. Move call to `.ShutdownInitiated` to outside of a loop, so that the `WatchChannel` always has the opportunity to terminate
> fix(provider): eliminate resource leaks causing OOM

- provider/cluster/inventory.go
- provider/cluster/service.go
We have some fail-safe code to clean up reservations. It's not a big deal. This error gets logged quite a bit in production however after EventLeaseClosed shows up, so I think we should just stop logging it
> fix(provider): Don't log errors for inventory not found

- provider/cluster/inventory.go
- provider/cluster/inventory_test.go
- types/resource.go
- types/resource_test.go
- types/resourcevalue.go
- types/resourcevalue_test.go
So we had two issues
1. Calling `.Sub()` on `ResourceUnits` was not idempotent. It mutated the receiver. This is wrong.
2. We had a race where we marked a deployment as allocated, so we consider it to be already in the resource counts from kube. But we don't fetch a new inventory data from kube, so this leads to reservations being made that should not be.
I wrote more tests around the provider's inventory code. All I really did here was
1. Correct a copy of a pointer to be a copy of a value
2. Don't process reservations after a deployment is marked `allocated` until we get a new update of the inventory from kubernetes
3. Update some tests that are failing as a result of this fix.
> fix(provider): Correct bugs around inventory management

- provider/cmd/shell.go
I think this got broken in a merge, the fix was pretty easy.
> fix(provider): fix the usage of flags in the lease-shell command

- make/test-integration.mk
The coverage script was broken till now. Previously, this script was expanding to following command:
```
GO111MODULE=on go test -tags= -coverprofile=coverage.txt \
-covermode=count \
-coverpkg=github.com/ovrclk/akash/app github.com/ovrclk/akash/app/params github.com/ovrclk/akash/client github.com/ovrclk/akash/client/broadcaster github.com/ovrclk/akash/client/docs
/statik github.com/ovrclk/akash/cmd/akash github.com/ovrclk/akash/cmd/akash/cmd github.com/ovrclk/akash/cmd/common github.com/ovrclk/akash/deploy/cmd github.com/ovrclk/akash/docgen github.co
m/ovrclk/akash/events github.com/ovrclk/akash/events/cmd github.com/ovrclk/akash/integration github.com/ovrclk/akash/manifest github.com/ovrclk/akash/pkg/apis/akash.network/v1 github.com/ovr
clk/akash/pkg/client/clientset/versioned …
```
> fix: Correct test coverage script

- go.mod
- go.sum
This PR fixes the broken `--home` flag after the cosmos@v0.43.0 upgrade.
---
title: ''
labels: ''
---
> fix: Fix broken `--home` flag

- sdl/v2.go
It looks like we just were not setting command in the SDL at all. This fixes that
> Use command for services from SDL

- provider/cluster/kube/client.go
- provider/cluster/types/types.go
- provider/gateway/rest/router.go
This fixes two things
1. Lease events had 0 for time, kubernetes never gives us this data so we can't provide it
2. There was a panic in the provider that caused it to crash. We were trying to cast nil to a type which obviously doesn't work
> fix lease events time

- provider/cmd/run.go
The value must be set before passing it in, obviously.
> bid deposit config

- go.mod
- go.sum
Github notified about a CVE so this version bump fixes it
> fix: Update gin dependency version due to CVE

- provider/bidengine/pricing_test.go
- provider/bidengine/testdata/usd_pricing_oracle.sh
- script/usd_pricing_oracle.sh
This PR adds a script that uses the current USD price of an AKT to calculate the bid price.
> feat: Bid pricing based on USD scale

- provider/gateway/rest/router.go
- provider/manifest/watchdog.go
- provider/manifest/watchdog_test.go
Fixes
1. only allow a manifest watchdog to be stopped once
2. log manifest errors
> manifest watchdog stop fix

- provider/cluster/kube/builder/builder.go
- provider/cluster/kube/builder/netpol.go
Tested on my v0.14.1-rc6 provider.
I am gonna prepare a patch for 0.14.1-rc6 as well.
```
$ cat dnsutils.yaml 
---
version: "2.0"
services:
dnsutils:
image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
command:
- "sh"
- "-c"
args:
- sleep 1d
expose:
- port: 8080
as: 80
to:
- global: true
profiles:
compute:
dnsutils:
resources:
cpu:
units: 1.0
memory:
size: 128Mi 
storage:
size: 128Mi
placement:
akash:
signedBy:
anyOf:
- "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
pricing:
dnsutils:
denom: uakt
amount: 100
deployment:
dnsutils:
akash:
profile: dnsutils
count: 1
```
```
/ # nslookup -vc kubernetes.default.svc.cluster.local
Server:		10.233.0.10
Address:	10.233.0.10#53
Name:	kubernetes.default.svc.cluster.local
Address: 10.233.0.1
```
```
/ # dig +noall +answer +tcp …
```
> fix(provider): kube-dns network policy selectors

- _docs/kustomize/akash-hostname-operator/deployment.yaml
- _docs/kustomize/akash-hostname-operator/ingress.yaml
- _docs/kustomize/akash-hostname-operator/kustomization.yaml
- _docs/kustomize/akash-hostname-operator/service.yaml
- integration/e2e_test.go
- provider/cmd/hostname_operator.go
- provider/cmd/hostname_operator_test.go
- provider/cmd/hostname_operator_types.go
There are sometimes CRDs from zombie or otherwise left over deployments that cause an error. Right now the hostname operator spins on that error.
The goal of this PR is to allow the hostname operator to move past that error by eventually just ignoring the problematic CRDs. They still should be removed but for now this is probably a best case workaround
**Changes**
1. Detect any errors correlating to a resource in kubernetes not found and track the count of them
2. Once the threshold is reached (3 by default) ignore subsequent events from those leases, they are probably a zombie
3. Ignored leases are tracked in a list that is pruned if it gets too large
4. Make all values that make sense to be configurable via flags, but should probably be set environmental variables
5. Add a read only …
> hostname operator  - ignore problematic namespaces

- provider/balance_checker_test.go
- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/bidengine/provider_attributes_test.go
- provider/cluster/lease_withdraw.go
- provider/cluster/manager.go
- provider/cluster/monitor_test.go
- provider/cmd/manifest.go
- provider/cmd/run.go
- provider/cmd/status.go
- provider/manifest/manager_test.go
- provider/manifest/watchdog_test.go
- provider/session/session.go
- provider/session/session_test.go
- testutil/channel_wait.go
There were a few issues brought up here that I fixed
1. If the provider finds a bid on startup, apply the standard timeout to it before closing
2. If the provider finds a bid on startup, make sure it is in the bid open state
3. If the provider finds a bid on startup that is very old, close it immediately
4. If the provider order goroutine gets a bid closed event for that order then terminate. This means someone did it with the CLI most likely
5. Don't close the bid on bid created. The bid is already in the `BidLost` state due to the way the market module is implemented. The network basically closes it for us, saving us fees.
**Code style stuff**
1. Remove `order.bidPlaced`. I don't know why this was a member variable. It is just a local variable now.
2. Add a helper for computing bid …
> Fix provider behavior around existing bids

- sdkutil/broadcast.go
- x/audit/client/cli/tx.go
- x/cert/client/cli/tx.go
- x/deployment/client/cli/tx.go
- x/market/client/cli/tx.go
- x/provider/client/cli/tx.go
Pass command context to the BroadcastTX allows tests to
properly handle context.Cancel
fixes #1432
> fix(sdkutil): get txhash from serialized tx rather than response

- _run/lite/Makefile
> fix(_run): add missing clean target for lite

- provider/cluster/kube/builder/deployment.go
- provider/cluster/kube/builder/settings.go
- provider/cluster/kube/builder/statefulset.go
- provider/cluster/kube/builder/workload.go
- provider/cmd/run.go
This PR adds the support for using docker pro accounts when kebernetes pulls images from docker.
Technically, this is achieved by creating a `podSpec` with `imagePullSecrets`.
The provider would first need to register their secrets with `kubectl` on their machine in order to use this feature. This can be done using following command:
```
kubectl create secret docker-registry <your-secret-name> --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
```
Then, they can supply the registered secret name to the provider daemon using the `--docker-image-pull-secrets-name` flag. This would make all the workloads running on a provider's cluster use the given secret to pull images from docker. Providers can also use the …
> Enable docker pro usage in kubernetes image pulls

- provider/bidengine/provider_attributes_test.go
fetch provider attributes to prevent call check from flapping between values 1 and 2
fixes fails like this https://github.com/ovrclk/akash/runs/4564809822?check_suite_focus=true#step:6:214
> fix(test): flapping call count on provider attributes mock

- validation/manifest.go
- validation/manifest_test.go
@arno01 found that a service name starting with a number never comes online in Kubernetes and causes all sort of errors & failures.
We already have some validation around this, so I just updated the regex & the associated tests to block out anything starting with a number. It never worked anyways.
> fix(sdl): Do not allow service names starting with a number

- _build/Dockerfile.akash
Just bumping the image to the current stable Debian release.
One of the reasons is that I have noticed that akash-node from Helm Charts [is using aria2](https://github.com/ovrclk/helm-charts/blob/64e02cb0fd8b83bf32beacc0a68d934a33ce0340/charts/akash-node/templates/configmap.yaml#L21) v1.34 from debian:buster, which is too old to understand TLS v1.3:
```
02/07 21:58:21 [WARN] aria2c had to connect to the other side using an unknown TLS protocol. The integrity and confidentiality of the connection might be compromised.
Peer: cosmos-snapshots.s3.filebase.com (135.148.54.72:443)
```
Made a simple test by building the Dockerfile.akash, running the "akash version" from inside, did not give an error.
PR for master -> https://github.com/ovrclk/akash/pull/1516
> akash image: bump debian version

- integration/e2e_test.go
- provider/cluster/kube/client_exec.go
- provider/cluster/kube/client_exec_test.go
- provider/cluster/kube/client_test.go
- provider/testutil/provider.go
In the implementation for the provider lease shell code that talks to kubernetes, just check that the pod is actually ready before launching a shell. If not, give the user a clear error message as to what is going on here.
I also added a bunch of tests for this code since it turned out to be to relatively easy.
> fix(provider): If a pod is not ready, do not try and launch a shell

- testutil/log.go
prevents data race in logger during tests
> fix(testutil): guard testWriter with mutex

- x/deployment/types/v1beta2/deposit_deployment_authorization.go
- x/deployment/types/v1beta2/types_test.go
If you have a cosmos SDK coin type and do `Sub()` it panics if the value goes negative. So you can't check the result with `IsNegative` or `IsZero`. You have to do the comparison before subtracting and stop there.
> fix: remove improper usage of IsNegative on cosmos sdk coin type

- x/cert/utils/utils.go
I think I made some sort of copy->paste error while performing this refactor. Fixing it here.
> fix(cli): return errors when checking for certificate presence

- .github/workflows/tests.yaml
- codecov.yml
v1 has been deprecated on [Feb 1 2022](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1)
ignore coverage of *.pb.gw.go files
> ci(codecov): update action to v2

- make/codegen.mk
- make/init.mk
- make/setup-cache.mk
- tools.go
protoc-gen-gocosmos uses replace in modules which prevents
direct install via link
refactor names of the variables related to protoc-gen-gocosmos
> build(codegen): install protoc-gen-gocosmos from vendor

- x/market/types/v1beta2/params.go
allows genereting test genesis with params identical to
the mainnet
> fix: set DefaultBidMinDeposit same value as mainnet-2

- Makefile
- make/init.mk
- make/lint.mk
- make/setup-cache.mk
- provider/cluster/monitor.go
- x/deployment/simulation/operations.go
- x/escrow/genesis.go
- x/market/simulation/operations.go
- x/provider/simulation/operations.go
fixes #ENG-286
speeds up lint process
replace deprecated linters
> build(lint): install and use golangci-lint from cache

- .goreleaser.yaml
- Makefile
- make/releasing.mk
use IS_STABLE to define docker image tag
fixes #ENG-287
> build: fix typo in prerel variable name

- x/market/keeper/keys/key.go
- x/market/keeper/keys/key_test.go
This disables querying by the secondary prefix, since it never got properly populated in the network upgrade.
The keys for the secondary prefix are still written to, just not queried. Otherwise this would wind up constituting a hard fork.
> fix(node): disable querying lease by provider secondary index

- provider/cmd/migrate_endpoints.go
- provider/cmd/migrate_hostnames.go
This adds the missing description of these commands
> fix(provider): add docstrings to migrate endpoint & hostname commands

- provider/cluster/kube/metallb/client.go
- provider/cluster/mocks/metallb_client.go
- provider/operator/ipoperator/ip_operator.go
- provider/operator/ipoperator/ip_operator_test.go
In the current code the operator won't pickup changes to the pools made in metal LB after it starts, at least not immediately.
This fixes that by periodically polling for the data & triggering a check each time the metal LB config maps change in k8s.
> fix(operator): have the IP operator immediately update availability of IPs

- provider/cluster/kube/cluster_ip_connections.go
- provider/cluster/util/ip_sharing_key.go
- provider/cluster/util/ip_sharing_key_test.go
The old regexp allowed partial matches, which is bogus and spurious. The regexp must validate the entire input string. It must be hashed if it fails.
> fix(provider): fix detection logic around names

- provider/cluster/kube/builder/netpol.go
This change should allow any incoming traffic to reach a service exposed via an IP lease. It's mean to be publicly exposed so this should be fine. I think this fixes the multi-node cluster problem I've been encountering on edgenet.
I was experimenting with specifically allowing the pod subnets, but there is lots of complexity in that. Also I'm not entirely sure that it should work that way. It may be a quirk of the way Calico is implemented.
If we're good with this change I'll make a PR for the provider-services as well.
> Add network policy for IPs

- provider/cluster/kube/builder/netpol.go
It looks like Scott found a bug here that's been there for a while
If the container port & external port is the same, everything works. If they are different, it does not work. The netpol must allow the container port to be accessed. The external port specified is completely irrelevant.
> fix(provider): change netpol to allow the internal container port

- .github/workflows/release-dry-run.yaml
- .github/workflows/release.yaml
- make/releasing.mk
> ci(release): defer tag detection to makefile when doing dry-run on branch

- .github/workflows/macos.yaml
- .github/workflows/proto.yaml
- .github/workflows/release-dry-run.yaml
- .github/workflows/release.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/sims.yaml
- .github/workflows/standardize-yaml.yaml
- .github/workflows/tests.yaml
previous versions are using node12 which is deprecated in favor of node16
fixes ovrclk/engineering#602
> ci: update actions

- cmd/akash/cmd/root.go
> fix: make txCmd and queryCmd public to be used by provider-services

- app/app.go
- go.mod
- go.sum
reflects akash version upgrade will be applied on
> fix: rename 01-ica-upgrade upgrade handler to v0.18.0

- cmd/akash/cmd/root.go
- util/cli/configs.go
remove use of basename as primary env prefix
the env prefixes must be set explicitly
fixes ovrclk/engineering#672
> fix(configs): fork cosmos-sdk intercept configs

- app/app.go
- app/app_configure.go
- app/app_test.go
- app/export.go
- app/sim_test.go
- app/types/app.go
- app/upgrades.go
- app/upgrades/akash_v0.15.0_cosmos_v0.44.x/upgrade.go
- app/upgrades/readme.md
- app/upgrades/v0.18.0/upgrade.go
- app/upgrades/v0.20.0/upgrade.go
- move keepers and app modules into dedicated struct with public members allows upgrade handlers to access necessary objects during initialization
- move each upgrade into dedicated package
refs akash-network/support#73
> refactor(app): upgrade handlers

- make/lint.mk
deadcode has been deprecated from golangci-lint 1.49
> fix(lint): replace deadcode linter with unused

- go.mod
- go.sum
- x/cert/client/cli/tx_cmd.go
- x/cert/utils/key_pair_manager.go
fixes issus when jsonparser in ledger cosmos-app
not liking bech address sent as data in binary format if test or file keyring used it will allow to decode old private keys for the mTLS cert
fixes akash-network/support#22
> fix: use from address as string to allow certs signed with ledger

- cmd/akash/cmd/root.go
- cmd/akash/main.go
- go.mod
- go.sum
- testutil/base.go
remove init of SDK Config and rely on one akash-api
Closes: #XXXX
---
I have...
> fix: bump akash-api to v0.0.12

- cmd/akash/cmd/root.go
- util/cli/configs.go
disable colored output by default
Closes: #XXXX
---
I have...
> refactor: default logger. log to stdout

- x/audit/genesis.go
- x/deployment/genesis.go
- x/gov/genesis.go
- x/inflation/genesis.go
- x/market/genesis.go
- x/provider/genesis.go
> feat(x): decode modules genesis state for testnetify command

- cmd/akash/cmd/genaccounts.go
- cmd/akash/cmd/root.go
- cmd/akash/cmd/testnetify/accounts.go
- cmd/akash/cmd/testnetify/cmd.go
- cmd/akash/cmd/testnetify/config.go
- cmd/akash/cmd/testnetify/escrow.go
- cmd/akash/cmd/testnetify/state.go
- cmd/akash/cmd/testnetify/util.go
- cmd/akash/cmd/testnetify/validators.go
- go.mod
- go.sum
> feat(cmd): implement testnetify command

- cmd/akash/cmd/genaccounts.go
fresh genesis may not have accounts yet
Closes: #XXXX
---
I have...
> fix(genaccounts): check if genesis accounts are present

- go.mod
- go.sum
- sdl/_testdata/simple-gpu.yaml
- sdl/full_test.go
- sdl/gpu.go
- sdl/gpu_test.go
- sdl/resources.go
- sdl/units.go
- sdl/v2_test.go
allow wildcards for GPU attributes in deployment messages
Closes: #XXXX
---
I have...
> feat: accont for gpu attributes

- x/escrow/keeper/keeper.go
* Use `floor` to prevent overflow.
> fix(escrow/keeper): always down

- _docs/adr/adr-001-network-upgrades.md
> feat(adr): adr 001 implementing network upgrade

- go.mod
- go.sum
- sdl/_testdata/service-mix.yaml
- sdl/_testdata/service-mix2.yaml
- sdl/_testdata/simple-with-ip.yaml
- sdl/expose.go
- sdl/gpu.go
- sdl/resources.go
- sdl/sdl.go
- sdl/sdl_test.go
- sdl/util/util.go
- sdl/util/util_test.go
- sdl/v2.go
- sdl/v2_ip_test.go
- sdl/v2_test.go
- testutil/base.go
- testutil/sdk.go
- testutil/types.go
- upgrades/software/v0.24.0/deployment.go
- x/deployment/client/cli/tx.go
- x/deployment/handler/handler_test.go
- x/deployment/keeper/grpc_query_test.go
- x/deployment/simulation/operations.go
- x/market/handler/handler_test.go
> feat: implement resource id and refactor sdl parsing

- tools/upgrade-info/main.go
> feat(tools): add upgrade info generator

- make/init.mk
> fix: remove redundant v prefix from detected version

- .envrc
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- make/releasing.mk
> ci: configure environment after installing go

- x/cert/utils/key_pair_manager.go
DecryptPEMBlock may not return error due to format quirks Try parse key instead, and if fail use legacy passowrd to open it
Closes: #XXXX
---
I have...
> fix: try parse private key instead of checking for error

- app/app.go
- app/decorators/min_commision.go
- app/export.go
- app/sim_test.go
- app/types/app.go
> fix(staking): validate MaxRate value of the commission

- meta.json
- tests/upgrade/upgrade_test.go
- tests/upgrade/v0.26.0/postupgrade.go
- tests/upgrade/workers_test.go
- upgrades/CHANGELOG.md
- upgrades/software/v0.26.0/init.go
- upgrades/software/v0.26.0/upgrade.go
- upgrades/upgrades.go
> feat(upgrade): create v0.26.0 network upgrade

- .envrc
> build(envrc): check min required version for direnv and bash

- tests/upgrade/upgrade_test.go
> test(upgrade): send test-cases config to each validator

- go.mod
- go.sum
- testutil/base.go
this change increase resources max limits
Closes: #XXXX
---
I have...
> chore: bump akash-api to v0.0.31

- go.mod
- go.sum
- x/market/simulation/operations.go
fixes NewMsgCreateBid with resource offer param
Closes: #XXXX
---
I have...
> chore: bump akash-api to v0.0.32

- go.mod
- make/test-upgrade.mk
- script/upgrades.sh
> fix: retract v0.28.0 release

- go.mod
- go.sum
- x/market/handler/handler_test.go
- x/market/handler/server.go
- x/market/keeper/keeper.go
- x/market/keeper/keeper_test.go
- x/provider/handler/handler_test.go
> fix(market): save resources offer to the bid

- cmd/akash/cmd/root.go
> feat: add ExecuteWithContext for root command

- make/releasing.mk
- script/tools.sh
> build: fix deprecated notices for goreleaser skip flags

- make/releasing.mk
> chore(releasing): nil GITHUB_TOKEN when release is only for local build

- go.mod
- go.sum
> chore(ledger): fixes error during ledger sign on lastes cosmos app

- testutil/network/network.go
prevents already in use error
Closes: #XXXX
---
I have...
> fix(testutil/network): preallocate all ports at once

- _docs/development-environment.md
> docs: update release instructions

- sdl/storage.go
- sdl/storage_test.go
- sdl/v2_1.go
* Add SDL support for `"ram"` storage class.
* `"ram"` volumes cannot be persistent or `ReadOnly`.
refs akash-network/support#179
> feat(sdl): `"ram"` storage class

- client/client.go
- go.mod
- go.sum
- x/audit/client/cli/tx.go
- x/cert/client/cli/tx.go
- x/cert/client/cli/tx_test.go
- x/deployment/client/cli/tx.go
- x/market/client/cli/tx.go
- x/provider/client/cli/tx.go
> feat(client): implement client opts

- x/cert/client/cli/grpc_rest_test.go
> fix(x/cert): cleanup grpc tests

- meta.json
- tests/upgrade/upgrade-v0.32.0.json
- tests/upgrade/upgrade_test.go
- tests/upgrade/v0.32.0/postupgrade.go
- tests/upgrade/workers_test.go
- upgrades/CHANGELOG.md
- upgrades/software/v0.32.0/init.go
- upgrades/software/v0.32.0/market.go
- upgrades/software/v0.32.0/upgrade.go
- upgrades/upgrades.go
- x/market/keeper/keeper.go
- x/market/keeper/keys/v1beta4/key.go
- x/provider/handler/handler_test.go
- x/provider/handler/server.go
> feat(upgrade): network upgrade v0.32.0

- .github/workflows/concommits.yaml
- .github/workflows/dispatch.yaml
- .github/workflows/labeler.yaml
- .github/workflows/release.yaml
- .github/workflows/stale.yaml
- .github/workflows/standardize-yaml.yaml
- .github/workflows/tests.yaml
> ci: bump actions

- upgrades/CHANGELOG.md
> docs: add changelog entry for v0.34.0 upgrade

- go.mod
- go.sum
fixes issue when deployment deposit from authz is claiming full amount but using only part of it. when deployment is closed exsiting funds will be returned to grantor and new authz must be issued.
Closes: #XXXX
---
I have...
> fix: bump akash-api to v0.0.67

- cmd/akash/cmd/testnetify/config.go
- cmd/akash/cmd/testnetify/state.go
- cmd/akash/cmd/testnetify/validators.go
use correctly derived consensus address
Closes: #XXXX
---
I have...
> fix(testnetify): use from address as operator

- _docs/adr/adr-001-network-upgrades.md
Path to `../upgrades/upgrades.go` should be `../../upgrades/upgrades.go` in [adr-001-network-upgrades.md](https://github.com/akash-network/node/blob/main/_docs/adr/adr-001-network-upgrades.md)
> chore: wrong link in adr-001-network-upgrades.md

- go.mod
- go.sum
- tests/upgrade/upgrade_test.go
- util/query/pagination.go
- util/query/pagination_test.go
- util/validation/address.go
- x/cert/keeper/grpc_query.go
- x/cert/keeper/grpc_query_test.go
- x/deployment/keeper/grpc_query.go
- x/deployment/keeper/grpc_query_test.go
- x/market/keeper/grpc_query.go
* Add pagination utility package with encoding/decoding functionality
* Implement pagination support in cert, deployment, and market queries
* Update validation utilities for address handling
* Add comprehensive test coverage for pagination functionality
> fix(query): add pagination support

- events/publish.go
- events/query.go
fixes issue with server side of websocket closing subscription due to client not reading events fast. this happens when block has substantial amount of txs thus events count can be > 1000. this implementation now just waits for event with block header then queries block info and parses events.
> refactor(event): parse events after querying block results

- cmd/akash/cmd/auth.go
- cmd/akash/cmd/root.go
- go.mod
- go.sum
fixes akash-network/support#323
Closes: #XXXX
---
I have...
> feat(cli): implement auth jwt command

- cmd/akash/cmd/auth.go
- go.mod
- go.sum
> fix: JWT CLI scopes documentation missing scopes
