- cmd/akash/context/context.go
- cmd/akash/deployment.go
- cmd/akash/provider.go
- cmd/akash/send.go
> context helpers

- cmd/akash/deployment.go
When the deployment it closed the status should be 0
> exit success

- _docs/design.md
- app/fulfillment/app.go
- app/lease/app.go
> Lease handling

- cmd/akash/base.go
- cmd/akash/main.go
- cmd/akashd/base.go
- cmd/akashd/main.go
> commands: non-zero exit status on error

- app/market/driver.go
- app/market/facilitator.go
- cmd/akash/deployment.go
- cmd/akash/provider.go
- cmd/common/monitor.go
- marketplace/monitor.go
`Error(msg,err)` -> `Error(msg,"error",err)`
fixes #98
> fix error logging

- cmd/akash/constants/constants.go
- cmd/akash/context/context.go
- cmd/akash/context/flags.go
- cmd/akash/deployment.go
fixes #87 
```sh
Aarons-MacBook-Pro:akash aaron$ ./akash deployment create filename -k master --wait
15F1834B146CDC956778F841457FDFE5063F9A0DD19A2785A420911D6DF01EC2
Waiting...
Group 1/1 Fulfillment: 15F1834B146CDC956778F841457FDFE5063F9A0DD19A2785A420911D6DF01EC200000000000000010000000000000002B8EBD6DFB42308C4C7F7CFC19F950EA0D7E1BE57C4F04866B49B9438E59A10DD
Group 1/1 Lease: 15F1834B146CDC956778F841457FDFE5063F9A0DD19A2785A420911D6DF01EC200000000000000010000000000000002B8EBD6DFB42308C4C7F7CFC19F950EA0D7E1BE57C4F04866B49B9438E59A10DD
```
> wait flag for deployment

- .gitignore
- .travis.yml
- Dockerfile
- Makefile
* docker: local builds (faster).
* travis: integration tests on more variants.
> osx: golang 1.10

- app/account/app_test.go
- app/deployment/app_test.go
- app/fulfillment/app_test.go
- app/lease/app_test.go
- app/market/driver.go
- app/order/app_test.go
- app/provider/app_test.go
- cmd/akash/context/flags.go
- cmd/akash/status.go
- cmd/akashd/start.go
- glide.lock
- glide.yaml
- marketplace/monitor.go
- node/amino.go
- node/util.go
- testutil/deployment.go
- testutil/fulfillment.go
- testutil/keys.go
- testutil/lease.go
- testutil/order.go
- testutil/provider.go
- util/initgen/builder.go
- util/initgen/dir.go
- util/initgen/dir_test.go
- util/initgen/helm.go
- util/initgen/helm_test.go
> tendermint libs: use overclock forks

- cmd/akash/deployment.go
- manifest/manifest_test.go
- manifest/verify.go
- provider/manifest/handler.go
- provider/manifest/handler_test.go
> manifest verification

- app/app.go
- app/app_test.go
- testutil/deployment.go
> Leases: transfer tokens

- .buildkite/pipeline.yml
- .buildkite/script/test.sh
- .buildkite/template.yml
- .codecov.yml
- Makefile
* run builds on our own AWS instances
* use codecov.io for code coverage
* travis-ci jobs still enabled for now
> ci: use buildkite

- Makefile
add `make install` to copy `akash` and `akashd` to `$GOPATH/bin`
> make: add install

- provider/grpc/server.go
> remove log

- _docs/deployment.yml
- _integration/cmp/account.go
- _run/kube/deployment.yml
- _run/multi/deployment.yml
- denom/denom.go
- sdl/_testdata/simple.yml
- sdl/v1_test.go
fixes: #277
send command
`akash send 10.10 14a95cb390fe0cb2b31b61bef64b207781998463`
`akash send 100.102 14a95cb390fe0cb2b31b61bef64b207781998463`
_deployment.yml_
```yaml
pricing:
web: .11
db: 10
```
> factional akash

- cmd/common/signal.go
- glide.lock
- glide.yaml
- provider/bidengine/config.go
- provider/bidengine/order.go
- provider/bidengine/service.go
- provider/bidengine/service_test.go
* skip orders greater than one cpu
* skip orders with max price too low
* price according to memory usage
fixes #291
fixes #295
> bidengine: bid parameters

- _docs/deployment.yml
- _docs/sdl.md
- _run/kube/deployment.yml
- _run/multi/deployment.yml
- glide.lock
- glide.yaml
- provider/bidengine/config.go
- provider/bidengine/order.go
- provider/bidengine/service_test.go
- provider/cluster/client.go
- provider/cluster/inventory.go
- provider/cluster/service.go
- provider/cluster/service_test.go
- provider/config.go
- provider/manifest/handler_test.go
- provider/service.go
- sdl/_testdata/simple.yml
- sdl/sdl.go
- sdl/v1.go
- sdl/v1_test.go
- testutil/deployment.go
- testutil/wait.go
> Bucket o changes

- manifest/auth.go
- manifest/manifest_test.go
> typo: tennant -> tenant

- _integration/cmp/base.go
- _run/common.sh
- _run/multi/env.sh
- _run/single/env.sh
- cmd/akash/session/base.go
- cmd/akash/session/flags.go
> akash: use testnet node foor default

- .github/CODEOWNERS
- cmd/akash/session/base.go
> akash: don't save config

- _docs/deployment.yml
- _integration/cmp/account.go
- _run/multi/deployment.yml
- cmd/akash/deployment.go
- denom/denom.go
- sdl/_testdata/profile-svc-name-mismatch.yml
- sdl/_testdata/simple.yml
- sdl/v1.go
- sdl/v1_test.go
- validation/pricing.go
* add `akash deployment validate <deployment.yml>`
* use micro akash instead of milli akash
> sdl: lookup pricing by compute profile name

- .github/CODEOWNERS
- cmd/akashd/start.go
> akashd: log at info level

- cmd/akash/key.go
- cmd/akash/provider.go
add new key management options:
- add display public key only for key show
- add display private key only for key show
- add new command `key import` add import private key
import provider run command:
add `--private-key` flag for `provider run`
> Simplify provider deployment with private key import during run

- cmd/akash/provider.go
- provider/cluster/client.go
- provider/cluster/kube/builder.go
- provider/cluster/kube/client.go
- provider/cluster/manager.go
- provider/cluster/monitor.go
- provider/cluster/service.go
- provider/session/session.go
> replace single service ingress with name based routing (#391)

- cmd/common/sdutil/sdutil.go
> cmd/deployment: display service mapping for each host

- provider/cluster/service.go
> provider/cluster: fix invalid slice handling

- .github/CODEOWNERS
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/community-issue-template.md
- README.md
> docs: add contributing guide

- .github/ISSUE_TEMPLATE/community-issue-template.md
- .github/PULL_REQUEST_TEMPLATE.md
- cmd/akash/deployment/create.go
- cmd/common/sdutil/sdutil.go
- go.mod
- go.sum
> github: add pull request template

- _run/multi/Makefile
- _run/multi/akash-node/templates/deployment.yaml
refs #413
---
title: ''
labels: ''
---
> akashd rpc: listen on all interfaces

- provider/grpc/server.go
> provider/grpc: remove bogus sleep

- go.mod
- go.sum
> upstream/uitable: fix IOR error during empty listing [#421]

- cmd/akashd/init.go
> genesis: set initial token supply to 100M AKT

- cmd/akash/provider.go
- go.mod
- go.sum
- provider/http/client.go
> query provider status concurrently with a 2 sec timeout

- x/deployment/types/errors.go
- x/provider/handler/handler.go
> use unique error codes

- Makefile
> keys: add build flags for ledger support

- client/client.go
- cmd/akash/provider.go
- provider/bidengine/order.go
- provider/bidengine/service.go
- provider/cluster/service.go
- provider/manifest/handler.go
- provider/session/session.go
- x/provider/client/cli/query.go
- x/provider/query/client.go
- x/provider/query/path.go
- x/provider/query/querier.go
- x/provider/query/types.go
- x/provider/types/errors.go
- x/provider/types/types.go
> provider/session: use full provider object

- CHANGELOG
- CHANGELOG.md
- go.mod
- go.sum
> bump SDK version to v0.38.1

- sdkutil/query.go
- x/deployment/query/client.go
- x/deployment/query/path.go
- x/deployment/query/querier.go
- x/deployment/query/rawclient.go
- x/market/client/rest/rest.go
- x/market/module.go
- x/market/query/client.go
- x/market/query/path.go
- x/market/query/rawclient.go
- x/provider/client/rest/rest.go
- x/provider/module.go
- x/provider/query/client.go
- x/provider/query/path.go
- x/provider/query/querier.go
- x/provider/query/rawclient.go
> Implement RawClient and few rest queries

- app/app.go
- simapp/app.go
- simapp/params/weights.go
- x/market/handler/keepers.go
- x/market/module.go
- x/market/simulation/genesis.go
- x/market/simulation/operations.go
- x/provider/simulation/operations.go
> Market simulation

- x/deployment/simulation/operations.go
- x/market/simulation/operations.go
- x/provider/simulation/operations.go
> Fix all msg execution issues and changed fees format

- go.mod
> Fix 'SecTrustedApplicationCreateFromPath' warnings

- app/app.go
- app/mac.go
- cmd/akashd/main.go
> Integrate gov and upgrade modules

- .goreleaser.yml
- _build/Dockerfile.akash
travis: remove matrix
fix test: add _run/kube/deployment.yml
gorel: update brew binaries
> DCS-6: configure gorelease and travis

- .github/workflows/sims.yaml
- Makefile
- app/app.go
- app/export.go
- app/sim_test.go
> Implement github actions for simulation tests

- x/deployment/types/id.go
- x/deployment/types/msgs.go
- x/market/types/id.go
- x/market/types/msgs.go
- x/provider/types/msgs.go
* add validation to ID types
* validate msg types using ID validation
fixes #470
> feat: x/*/types - validate IDs

- .buildkite/script/test.sh
- Makefile
Improve CI build times
* remove unnecessary image-bin builds.
* remove unused targets
> feat: ci - reduce image-bin invocations

- integration/deployment_test.go
- x/deployment/types/types.go
- x/market/keeper/keeper.go
- x/market/types/types.go
Make state values an invalid state.
fixes #520
> feat: guard default states

- .buildkite/script/test.sh
- Makefile
> ci: re-enable lint

- go.mod
- x/deployment/handler/endblock.go
- x/deployment/handler/keepers.go
- x/market/keeper/keeper.go
- x/market/keeper/keeper_test.go
- x/market/types/types.go
> feat: prevent duplicate active orders

- x/market/handler/handler.go
- x/market/keeper/keeper.go
- x/market/simulation/operations.go
- x/market/types/errors.go
> feat: prevent duplicate bids

- x/deployment/client/cli/tx.go
- x/deployment/handler/handler.go
- x/deployment/keeper/keeper_test.go
- x/deployment/simulation/operations.go
- x/deployment/types/codec.go
- x/deployment/types/msgs.go
- x/market/keeper/keeper_test.go
- x/market/types/codec.go
- x/market/types/msgs.go
- x/provider/client/cli/tx.go
- x/provider/handler/handler.go
- x/provider/keeper/keeper_test.go
- x/provider/simulation/operations.go
- x/provider/types/codec.go
- x/provider/types/msgs.go
> refactor(x): update message names

- .github/workflows/tests.yml
- .golangci.yaml
fixes #586
Make config as per spec
Run linters in github workflow with config
> ci: refactor .golangci-lint

- .github/workflows/tests.yml
- x/market/query/types.go
Tiny change... Updated test.yml.
fixes #544
> fix: deduplicate matching TODO strings

- app/app.go
- app/sim_test.go
> Modify init genesis order

- sdl/v1.go
- x/deployment/types/types.go
- x/market/types/types.go
- x/provider/config/config.go
- x/provider/types/types.go
> refactor: change attribute types

- app/app.go
> Add cygni upgrade handler

- .github/workflows/tests.yml
- pkg/apis/akash.network/v1/types.go
- pkg/client/informers/externalversions/generic.go
- provider/bidengine/service.go
- provider/cluster/inventory.go
- x/deployment/query/querier.go
- x/deployment/types/msgs.go
- x/market/keeper/keeper.go
- x/market/query/querier.go
- x/market/types/types.go
fixes #543
combine if statements executing same bodies
> refactor: fixes gocritic complains

- client/client.go
- client/extra.go
- provider/bidengine/service.go
- x/deployment/client/cli/flags.go
- x/deployment/client/rest/params.go
- x/deployment/query/client.go
- x/deployment/query/path.go
- x/deployment/query/querier.go
- x/deployment/query/rawclient.go
- x/deployment/query/types.go
- x/deployment/types/types.go
- x/market/client/cli/flags.go
- x/market/client/rest/params.go
- x/market/query/client.go
- x/market/query/path.go
- x/market/query/querier.go
- x/market/query/rawclient.go
- x/market/query/types.go
- x/market/types/types.go
> refactor: move filters to query package

- app/app.go
- app/tools.go
- x/deployment/ante/ante.go
- x/deployment/handler/handler.go
> feat: implement AnteHandler for Deployment

- events/publish.go
- events/publish_test.go
- events/query.go
- provider/cmd/run.go
- testutil/sdk.go
- x/deployment/types/event.go
* `./events`: re-add listening to tx events
* `./x/deployment/types`: fix close deployment tx
* `./provider/cmd/run`: non-colorized logging
* `./testutil`: coin generator.
> bugfix: fix events

- README.md
> docs: set up codecov badge

- x/deployment/handler/handler_test.go
- x/market/handler/handler_test.go
- x/provider/handler/handler_test.go
remove unused AccAddress generation
replace type check for sdk.Result with require.NotNil
> refactor: cleanup tests code

- app/app.go
- x/market/types/id.go
- x/provider/handler/handler.go
- x/provider/handler/handler_test.go
- x/provider/module.go
- x/provider/simulation/operations.go
- x/provider/types/errors.go
> fix: reject updates on provider attributes

- .github/workflows/integration.yaml
- .github/workflows/tests.yaml
- app/app.go
- cmd/akashctl/main.go
Disable akash modules for mainnet release.
> chore: trim akash modules for mainnet release

- _run/common.mk
- _run/lite/Makefile
> feat: _run/lite - remove "stake" token

- x/market/keeper/keeper.go
- x/market/keeper/key.go
> Improve bid and order search with prefix

- cmd/akashctl/main.go
- events/cmd/root.go
> Add `akashctl events` command

- .github/workflows/stale.yaml
Auto-reap stale PRs:
* add `stale` label after 10 days.
* close after five days.
> ci: stale pr reaper

- _run/kube/Makefile
- _run/kube/README.md
- _run/kube/deployment.yaml
- _run/kube/kind-config.yaml
- _run/kube/kind.mk
- _run/lite/README.md
- _run/lite/deployment.yaml
- provider/service.go
- script/setup-kind.sh
Checkpoint on `_run/kube` dev environment.
* `_run/lite`: update readme
* `_run/lite`: increase lease price
* `_run/kube`: update readme
* `_run/kube`: configure, use `kind` to deploy apps
* `provider/service`: fix NPE.
fixes #695
fixes #620
> devenv: _run/kube

- _run/common.mk
- _run/kube/Makefile
- _run/kube/README.md
- _run/kube/kind-config-80.yaml
- _run/kube/kind.mk
Add an option to proxy localhost:80 to your app
to play nice with kubernetes ingresses.
> devenv: add browseable option to _run/kind

- provider/cluster/types.go
- provider/cmd/leaseStatus.go
- provider/cmd/root.go
- provider/cmd/serviceStatus.go
- provider/cmd/status.go
- provider/gateway/client.go
- x/market/client/cli/flags.go
> feat: implement status commands

- provider/cmd/run.go
* `provider/cmd`: read more environment variables
> feat: provider: read environment variables

- _docs/examples/provider/.gitignore
- _docs/examples/provider/README.md
- _docs/examples/provider/kube-gce.md
- _docs/kustomize/akash-provider/service.yaml
Full example hosted on Testnet+GCE
> docs: examples/provider - full testnet+gce

- _docs/examples/provider/README.md
- _docs/examples/provider/kube-gce.md
- _docs/kustomize/akash-provider/deployment.yaml
- _docs/kustomize/akash-provider/kustomization.yaml
- provider/cluster/kube/settings.go
* _docs/kustomize: add ingress-expose-lb-hosts config
* _docs/examples/provider: gcp -> gce
* various instruction improvements
> docs: fixup example

- provider/gateway/router.go
> fix: return http 404 if lease not found

- events/publish_test.go
- sdkutil/event.go
- x/deployment/keeper/keeper.go
- x/deployment/types/event.go
- x/market/keeper/keeper.go
- x/market/types/event.go
- x/provider/types/event.go
> feat: events - expose name, module

- events/publish_test.go
- provider/manifest/service.go
- x/deployment/handler/handler_test.go
- x/deployment/keeper/keeper.go
- x/deployment/types/event.go
- x/deployment/types/events_test.go
- x/provider/handler/handler_test.go
- x/provider/keeper/keeper.go
- x/provider/types/event.go
- x/provider/types/events_test.go
> refactor: use past tense for events

- x/deployment/handler/handler_test.go
- x/deployment/keeper/keeper.go
> fix: emit EventDeploymentClose

- go.mod
- go.sum
> Update SDK and TM versions

- _docs/sdl.md
- manifest/types.go
- provider/cluster/kube/builder.go
- sdl/v1.go
> fix: include `command` key in services

- cmd/akashctl/main.go
- events/cmd/root.go
fixes #730 issue with viper when setting flags in cobra commands from env
> fix: commands to accept common sdk params

- provider/cmd/root.go
> fix: bind node flag for provider command

- _docs/examples/provider/.gitignore
- _docs/examples/provider/README.md
- _docs/examples/provider/kube-gce.md
- go.mod
- go.sum
small docs fixes.
tm bump.
This is the `v0.7.8-rc3` tag, but squashed.
> `v0.7.8-rc3`: tm-bump, doc fixes.  

- _docs/kustomize/akash-provider/deployment.yaml
- _docs/kustomize/akash-provider/kustomization.yaml
- _run/single/kustomize/akash-provider/kustomization.yaml
- provider/cluster/kube/settings.go
More params, including:
* pricing
* validation
fixes #772
> kustomize/akash-provider: more params

- README.md
- _docs/examples/provider/kustomization.yaml
- _run/single/kustomize/akashd/kustomization.yaml
Some of these are unnecessary but are left to illustrate
how to change the image tag.
> kustomize: use latest image

- godownloader.sh
`akashctl` -> `akash` binary naming.
> godownloader script typo fix

- .gitignore
- Makefile
- script/protocgen.sh
> feat: install protobuf tools into local cache

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- Makefile
ledger uses github.com/zondax/hid which includes some C files
in order to get ledger detected akash has to deal with CGO
and crosscompilation
fix is using Goreleaser packed in
https://github.com/gythialy/golang-cross Docker image
with bunch of toolchains for crosscompilation
> ci: fix crosscompile issue backport from master

- .codecov.yaml
- .github/workflows/standardize-yaml.yaml
- codecov.yml
it seem codecov does not recognize config file with `.yaml` extension
> ci: codecov expects file codecov.yml

- .github/workflows/macos.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- .gitignore
- .goreleaser-docker.yaml
- .goreleaser.yaml
- Makefile
- README.md
- script/semver.sh
ledger uses github.com/zondax/hid which includes some C files
in order to get ledger detected akash has to deal with CGO
and crosscompilation
fix is using Goreleaser packed in
https://github.com/troian/golang-cross Docker image
with bunch of toolchains for cross-compilation
Define goreleaser build flags in makefile. All goreleaser runs should be now done only through make
Use goreleaser to build test image
> ci: fix crosscompile issue

- .clang-format
- buf.yaml
- make/mod.mk
- make/proto.mk
- make/setup-cache.mk
- proto/akash/attribute.proto
- proto/akash/deployment/deployment.proto
- proto/akash/deployment/genesis.proto
- proto/akash/deployment/group.proto
- proto/akash/deployment/query.proto
- proto/akash/market/bid.proto
- proto/akash/market/genesis.proto
- proto/akash/market/lease.proto
- proto/akash/market/order.proto
- proto/akash/market/query.proto
- proto/akash/provider/genesis.proto
- proto/akash/provider/provider.proto
- proto/akash/provider/query.proto
- proto/akash/resource.proto
- proto/akash/resourcevalue.proto
- script/protocgen.sh
fix .clang-format config
install clang-format from default homebrew keg
> refactor: include external proto from cosmos/third_party

- buf.yaml
lints only proto files related to akash
> chore: update buf ignore lists

- buf.yaml
> fix: update reference config for buf tool

- .goreleaser-docker.yaml
- .goreleaser.yaml
kudos to @alessio for suggesting -trimpath
Co-authored-by: Alessio Treglia <alessio@debian.org>
merge after #846
> refactor: use anchors to deduplicate flags in goreleaser

- Makefile
- go.sum
- make/codegen.mk
- make/setup-cache.mk
- script/protocgen.sh
> fix: install protoc-gen-cosmos into cache dir

- x/market/client/cli/cli_test.go
> fix(integration): increase wait time

- sdl/coin_test.go
- sdl/full_test.go
- x/market/types/events_test.go
Just getting rid of "akt" in the tests
> test: make sure all tests are using uakt for denomination fixes #771

- go.sum
- make/setup-cache.mk
> chore(make): silent command detection failure

- provider/bidengine/order.go
- provider/bidengine/order_test.go
There is a race in one of the tests I added. It passes for me locally and also on @troian 's machine. It is failing in CI sometimes.
My solution for now is to add a channel that is only used during the unit test to avoid the race condition.
> test(provider): Fix a race in the bidengine

- _docs/kustomize/akash-provider/deployment.yaml
@ropes and myself noticed I missed the full name of the env. vars. in the kustomize YAML used for the provider. Fixing that here.
> fix(provider): Correct the kustomize yaml used for the provider

- x/deployment/keeper/keeper.go
- x/deployment/keeper/keeper_test.go
- x/market/client/cli/cli_test.go
- x/market/handler/keepers.go
- x/market/handler/msg_server.go
note: does not add "paused" state so as to not affect state
schema
refs #944
> feat(deployment): group close on bidclose

- provider/cluster/kube/builder.go
> fix(kubeapi): set pod run user policy to RunAsUserStrategyRunAsAny

- provider/cluster/kube/client.go
> fix(pod-security): disable pod security policies

- client/broadcaster/client.go
- client/broadcaster/serial.go
- client/broadcaster/serial_test.go
- provider/cluster/kube/apply.go
- provider/cluster/kube/builder.go
1. don't increment sequence number on failed transactionx
1. for response code 0x20, attempt to adjust sequence number
refs #955
> fix(broadcaster): adjust broadcaster sequence

- provider/cluster/kube/apply.go
- provider/cluster/kube/builder.go
- provider/cluster/kube/k8s_integration_test.go
- provider/cluster/monitor.go
> chore: comment unused code to stop linter complains

- _run/common.mk
- x/audit/module.go
> fix(audit): validate genesis for audited attr

- provider/cluster/kube/client.go
- provider/cluster/kube/settings.go
- provider/cluster/types/types.go
- provider/cmd/run.go
> feat(provider-gateway): hostname for exposed ports

- go.mod
- go.sum
- provider/cluster/kube/builder.go
- provider/cluster/kube/client.go
- provider/cluster/kube/deployment_test.go
- provider/cluster/kube/k8s_integration_test.go
- provider/cmd/run.go
* deep-copy to avoid duplicates
* remove unused `host` argument
fixes #972
> fix(ingress hosts): stable hostnames

- README.md
finish off "the following packages"
---
title: ''
labels: ''
---
Added the list of packages added to $PATH
It completes a sentence in the Readme.
> The following packages

- .github/workflows/tests.yaml
- README.md
* update `GOLANG_VERSION` secret to `~1.15.6`
fixes #997
> fix(ci): remove unused parameters

- provider/cluster/kube/builder.go
Add `LeaseID` fields to manifest and namespace to make
search tooling easier.
fixes #989
> feat(cluster): add LeaseID fields to labels

- _docs/kustomize/networking/namespace.yaml
> fix(k8s labels): always include akash.network=true

- x/deployment/types/errors.go
- x/deployment/types/msgs.go
- x/deployment/types/msgs_test.go
- x/deployment/types/types.go
> fix: assert deployment version length

- .github/workflows/release.yaml
> ci: run release dry run with skip validate on branches

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yaml
- .github/workflows/release.yaml
- Makefile
- go.mod
- go.sum
- make/releasing.mk
- make/setup-cache.mk
- script/genchangelog.sh
> ci(changelog): generate changelog on releases

- cmd/akashd/cmd/genaccounts.go
- go.mod
- go.sum
> Bigbang testnet phase-3:  v0.41.0

- _run/common-commands.mk
- _run/single/Makefile
- _run/single/README.md
> docs(_run/single): update readme

- .github/workflows/k8s-integration.yaml
- .github/workflows/macos.yaml
- .github/workflows/release.yaml
- .github/workflows/sims.yaml
- .github/workflows/tests.yaml
set golang-cross version same value as setup-go@v2
> ci(go): fix go version read from env

- x/cert/handler/handler_test.go
- x/cert/keeper/keeper.go
- x/cert/keeper/keeper_test.go
- x/cert/types/errors.go
> refactor(cert): allow multiple active certificates for an account

- .github/workflows/release.yaml
dry-run creates files in dist with sudo rights
> ci(gorelease): for remove dist before starting release

- x/cert/client/cli/tx.go
- x/cert/keeper/grpc_query.go
- x/cert/utils/utils.go
commit certificate if not present on chain
> fix(cert): encode pubkey to PEM when loading from file

- integration/test_helpers.go
* remove artifacts left from pulling @troian's bf6770
@troian I think I must have pulled some in-flight work from your branch.  Happy to keep these, but they're causing lint failures.  Let me know how you want to deal with it.
> fix(lint): fix integration lint issues

- testutil/types.go
> test(testutil): increase default stake amount of test network

- proto/akash/provider/v1beta1/provider.proto
- testutil/base.go
- testutil/provider.go
- x/provider/handler/handler_test.go
- x/provider/handler/server.go
- x/provider/types/errors.go
- x/provider/types/msgs.go
- x/provider/types/provider.pb.go
- x/provider/types/types.go
> feat(provider): implement info fields

- app/app.go
- app/app_configure.go
- testutil/state/suite.go
- x/deployment/keeper/keeper.go
- x/deployment/keeper/keeper_test.go
- x/deployment/types/errors.go
- x/deployment/types/types.go
- x/escrow/keeper/keeper.go
- x/escrow/keeper/keeper_test.go
- x/market/hooks/external.go
- x/market/hooks/hooks.go
- x/market/keeper/keeper.go
- x/market/module.go
- x/provider/module.go
* unify market, deployment escrow hooks
* ensure orders closed when deployment closed
* fix escrow account settled-at bug
* fix group pause validation bug
fixes #1098
> refactor(hooks): refactor escrow hooks

- _docs/mtls.md
> docs(cert): certificates cookbook

- _run/common-commands.mk
- _run/kube/Makefile
- _run/kube/README.md
- _run/lite/Makefile
- _run/single/Makefile
- _run/single/deployment2.yaml
- provider/cluster/client.go
- provider/cluster/kube/client.go
- provider/cluster/kube/k8s_integration_test.go
- provider/cluster/mocks/client.go
- provider/cluster/mocks/read_client.go
- provider/cluster/types/types.go
- provider/cmd/helpers.go
- provider/cmd/leaseEvents.go
- provider/cmd/leaseLogs.go
- provider/cmd/root.go
- provider/cmd/serviceStatus.go
- provider/cmd/test_helpers.go
- provider/gateway/rest/client.go
- provider/gateway/rest/middleware.go
- provider/gateway/rest/path.go
- provider/gateway/rest/router.go
example of output
fixes #1035
<details>
<summary>events output example</summary>
```
❯ make provider-lease-events
../../akash --home "./cache" --node "tcp://akash.localhost:80" "--keyring-backend=test" provider lease-events \
--follow \
--dseq "1"     \
--from "main" \
--provider "akash1e4adtnd546z49cvuw6g3x2cp5jcq00y5e6x39f"
{
"type": "Normal",
"time": "0001-01-01T00:00:00Z",
"reason": "Pulled",
"object": {
"kind": "Pod",
"namespace": "q48li8e671c01aff7hkg642hk515u7r8efmuajq73pthu",
"name": "web-5f9ff4bfc8-xrrz6"
}
}
{
"type": "Normal",
"time": "0001-01-01T00:00:00Z",
"reason": "Sync",
"object": {
"kind": "Ingress",
"namespace": "q48li8e671c01aff7hkg642hk515u7r8efmuajq73pthu",
"name": "web"
}
}
{
"type": "Normal",
"time": "0001-01-01T00:00:00Z",
"reason": "Scheduled",
"object": {
"kind": …
```
> feat(provider): refactor gateway api

- provider/gateway/rest/client.go
> chore(provider): remove debug println

- go.mod
- go.sum
This has the latest version of our fix. Moving to this tag:
https://github.com/ovrclk/cosmos-sdk/tree/v0.41.4-akash-2
> fix: raise up akash cosmos fork version to get new multisig fix

- .goreleaser-docker.yaml
- .goreleaser.yaml
> ci(release): remove push to docker.io

- cmd/akash/cmd/root.go
> fix(cmd): silence usage print on command error

- x/audit/keeper/keeper.go
- x/audit/types/errors.go
> fix(audit): return sdk error if attr key not found

- x/audit/client/cli/tx.go
> fix(attr): query all provider attributes if none provided via arguments

- deploy/cmd/create.go
- x/cert/utils/utils.go
> fix(deploy): check client certificate exists before creating deployment

- provider/cmd/helpers.go
> fix(provider): add home flag to provider cli

- .goreleaser.yaml
- Makefile
> fix(build): segfault when resolving user id to name on linux

- app/migrations/akashnet_2_upgrade_1.go
- go.mod
- go.sum
> fix(app/migrations): handle not found errors

- x/provider/client/cli/tx.go
- x/provider/config/config.go
> fix: add provider info field when parsing config

- go.mod
- go.sum
> build(go): set minimum go version to 1.16

- go.mod
- go.sum
> fix(mod): replace underlying mods for ledger-cosmos-go

- .github/workflows/proto.yaml
> ci(proto): add setup go for lint step

- deploy/cmd/create.go
- provider/cmd/leaseEvents.go
- provider/cmd/leaseLogs.go
- provider/cmd/leaseStatus.go
- provider/cmd/manifest.go
- provider/cmd/serviceStatus.go
- provider/gateway/rest/client.go
- x/cert/utils/utils.go
- x/deployment/client/cli/tx.go
> fix(provider): query certificate status prior using gateway

- sdl/_testdata/deployment-svc-mismatch.yaml
- sdl/_testdata/simple2.yaml
- sdl/v2.go
- sdl/v2_test.go
> fix(sdl): use service name to find expose endpoints

- README.md
> docs(platform): list Apple M1 as supported

- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/bidengine/pricing.go
- provider/bidengine/pricing_test.go
- provider/service.go
Add an env. var. of AKASH_OWNER to the bid pricing script
> feat(provider): set AKASH_OWNER env. var. for bid pricing script

- x/cert/keeper/grpc_query.go
- x/cert/keeper/grpc_query_test.go
> fix(x/cert): query with pagination does not work

- validation/manifest.go
- validation/manifest_test.go
Just fixed a missing escape in my regex
> fix(provider): Allow the hostname with a dash in SDL

- provider/cluster/inventory.go
This just breaks out the reservations metrics into pending & active. Also added some logging around the number of reserve & unreserve calls that succeed.
> fix(provider): add more debugging around inventory

- provider/cmd/leaseStatus.go
- provider/cmd/serviceStatus.go
- x/deployment/client/cli/flags.go
- x/deployment/client/cli/query.go
- x/deployment/client/cli/tx.go
- x/escrow/client/cli/query.go
- x/market/client/cli/bid.go
- x/market/client/cli/cli_test.go
- x/market/client/cli/flags.go
- x/market/client/cli/lease.go
- x/market/client/cli/test_helpers.go
- x/market/client/cli/tx.go
> fix(cli): make owner flag optional

- _docs/kustomize/akash-node/ingress.yaml
- _run/common-base.mk
- _run/common-commands.mk
- _run/common-kind.mk
- _run/common.mk
- _run/single/Makefile
- _run/single/README.md
- _run/single/kind-config.yaml
- _run/single/kustomize/akash-node/.gitignore
- _run/single/kustomize/akash-node/docker-image.yaml
- _run/single/kustomize/akash-provider/.gitignore
- _run/single/kustomize/akash-provider/docker-image.yaml
> fix(_run): wrong path to client/server cache directories

- provider/balance_checker.go
- provider/balance_checker_test.go
- provider/cluster/lease_withdraw.go
- provider/cmd/run.go
- provider/cmd/shell.go
- provider/config.go
- provider/service.go
This makes the stuff around the withdrawal configurable.
I also put in a metric for provider balance while I was working on this.
> feat(provider): make withdrawal configurable

- CONTRIBUTING.md
We don't use Matrix anymore so I put in more relevant links
> fix(docs): update links in CONTRIBUTING.md

- x/deployment/client/cli/flags.go
Fixes https://github.com/ovrclk/akash/issues/1324
```
make test-e2e-integration
```
> Fix e2e test failing due to owner flag.

- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/cluster/inventory.go
- provider/cluster/inventory_test.go
Fixes https://github.com/ovrclk/akash/issues/1243 and https://github.com/ovrclk/akash/issues/1317
```
Test_OrderCloseBeforeReserveReturn
```
> Restore inventory on cancel reservation.

- provider/bidengine/config.go
- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/cmd/run.go
- provider/config.go
- provider/service.go
Fixes https://github.com/ovrclk/akash/issues/715
> Match provider config on order bid.

- x/deployment/client/cli/flags.go
This PR exports `deploymentIDOptions` struct and its fields. It is required for `akcmd`.
---
title: ''
labels: ''
---
> chore: Export DeploymentIDOptions

- types/resource.go
The fixes the resource units `.Add` receiver not to mutate things
> Fix Resource Units .Add function.

- _run/ingress-nginx.yaml
- _run/kube/Makefile
- provider/cluster/kube/client.go
- provider/cluster/types/types.go
- provider/gateway/rest/router.go
- types/resource.go
> fix lease events time

- script/shellcheck.sh
> ci(spellcheck): ignore scripts in .git directory

- script/provider_migrate_to_hostname_operator.md
Add some more details into the document for the upgrade
> update v0 14 0 upgrade docs

- script/provider_migrate_to_hostname_operator.md
I got some feedback from one of  our providers about difficulties encountered, this includes it into the doc.
> community provider feedback

- provider/bidengine/order_test.go
> test(bidengine): improve type assertion to dump type description

- x/deployment/types/v1beta2/validation_config.go
> Update container limits to support more workloads

- provider/cmd/clusterns.go
- provider/cmd/root.go
> feat(cli): provider show-cluster-ns command

- provider/cmd/clusterns.go
- provider/cmd/root.go
> feat(cli): provider get-cluster-ns command

- provider/bidengine/config.go
- provider/bidengine/order.go
- provider/bidengine/order_test.go
- provider/config.go
- provider/service.go
- validation/constants/constants.go
- x/deployment/client/cli/tx.go
> fix(sdl): check volume counts to not exceed limits

- provider/cluster/kube/inventory.go
> fix: Add taint check

- _run/common.mk
> chore(_run): add rosetta-run target

- _run/common-kind.mk
Providers can add Loki to their kube clusters for storing pod logs. This PR adds a make target to simplify the process.
The `loki-stack` helm chart is preset to scrap logs from all the pods running on the cluster using `promtail`. It can always be configured as per provider's needs.
> Integrate Loki with Kube cluster

- provider/cluster/kube/inventory.go
> refactor(inventory): do not log ignored node while iterating pods

- provider/cmd/manifest.go
> fix: expand error message when manifest send fails

- validation/manifest.go
- validation/manifest_test.go
Same as other PR, but updating master
> fix(sdl): Do not allow service names starting with a number

- provider/cluster/kube/client_exec.go
- provider/gateway/rest/router.go
> refactor: use Services api to check if lease is up

- .goreleaser.yaml
- make/init.mk
- make/releasing.mk
explicitly set compiler for each target in goreleaser.yaml
> build: go 1.17.6 and update path to goreleaser image

- provider/cluster/kube/inventory.go
- provider/config.go
> fix(inventory): set timeout to request for inventory operator

- provider/cluster/kube/inventory.go
> refactor(inventory): remove log for node taints

- _run/common.mk
enables all transactions _run examples to work
in real world examples with tx fees
> refactor(_run): run node with min gas prices set

- client/broadcaster/client.go
- client/broadcaster/serial.go
- sdkutil/broadcast.go
> fix(provider): add gas addjustment in auto mode

- .github/workflows/k8s-integration.yaml
- .github/workflows/macos.yaml
- .github/workflows/proto.yaml
- .github/workflows/sims.yaml
- .github/workflows/tests.yaml
> ci: fetch full repo history for all code related actions

- provider/cmd/leaseEvents.go
- provider/cmd/leaseLogs.go
- provider/cmd/leaseStatus.go
- provider/cmd/serviceStatus.go
> fix(provider): set args count validation for lease commands

- app/app.go
until the inflation calculator gets fixed
> build(app): suppress lint for unused code

- .gitignore
- .vscode/settings.json
> build: gitignore .vscode

- go.mod
- go.sum
> fix: bump hid package to v0.11.0

- provider/cluster/kube/inventory.go
- provider/cluster/kube/inventory_test.go
add kube inventory tests
fixes #SUPPORT-108
> fix(provider): inventory adjustment for multiple replicas

- .github/workflows/k8s-integration.yaml
> ci(e2e): run e2e on all changes to the provider

- provider/balance_checker.go
- provider/cluster/manager.go
> fix(provider): remove waitgroup for lease withdraw

- _docs/kustomize/akash-ip-operator/cluster_role.yaml
- _docs/kustomize/akash-ip-operator/rbac.yaml
The new code I added queries the config maps, so we need the service account to have permission to do so
> fix(kustomize): add permission for the IP operator to watch config maps

- .github/CODEOWNERS
> ci: update codeowners

- .github/workflows/release-dry-run.yaml
- .github/workflows/release.yaml
> ci(release): guess temporary tag for dry-run releases on branches

- .github/workflows/sims.yaml
- .github/workflows/standardize-yaml.yaml
- README.md
fix the link to simulations badge
> refactor(ci): replace space with hyphen in jobs names

- .github/workflows/release-dry-run.yaml
- .github/workflows/release.yaml
> ci: update docker actions

- godownloader.sh
> fix(godownloader): adjust darwin arch to download universal binary

- .envrc
- Makefile
- README.md
- doc/development-environment.md
- make/init.mk
> docs: document dev environment

- .github/workflows/shellcheck.yaml
- go.mod
- make/init.mk
- script/semver.sh
go version in go.mod MUST ==$(GO_MIN_REQUIRED)
installed go version MUST ==$(GO_MIN_REQUIRED)
refs ovrclk/engineering#668
> build: ensure go version match

- .github/workflows/release.yaml
- .goreleaser.yaml
homebrew formula will be updated by sending the event
to the ovrclk/homebrew-tap
> build(goreleaser): remove homebrew from goreleaser

- make/releasing.mk
> fix(build): remove --privileged flag from release target

- cmd/akash/cmd/root.go
> fix(config): return error if env bind to flag fails

- go.mod
- go.sum
> fix(RPC): enable websocket via TLS

- script/semver.sh
> fix(scripts): remove redundant exit

- install.sh
> fix: remove commented rm from install.sh

- .github/workflows/release.yaml
> ci(release): notify homebrew-tap with new release

- .github/workflows/release-dry-run.yaml
- .github/workflows/release.yaml
- Makefile
- script/genchangelog.sh
- script/is_prerelease.sh
- script/mainnet-from-tag.sh
> refactor(scripts): use exit code in scripts instead of echo

- .github/workflows/release.yaml
> ci(release): remove unused MAINNET env

- Makefile
- make/releasing.mk
> refactor(build): remove references to homebrew configs

- .github/workflows/wip.yaml
> ci: add WIP action

- .github/workflows/concommits.yaml
> ci: add conventional commits check

- .goreleaser-docker.yaml
- .goreleaser.yaml
- make/releasing.mk
> refactor(build): allow build docker images to custom registry

- .github/workflows/wip.yaml
> ci(wip): refactor keywords

- .gitignore
> chore(mod): .gitignore go workspace files

- app/ante.go
- app/app.go
> feat: init ante decorators list manually

- app/ante.go
- app/app.go
- app/app_configure.go
- app/decorators/min_commision.go
- x/staking/alias.go
- x/staking/genesis.go
- x/staking/keeper/keeper.go
- x/staking/module.go
- x/staking/simulation/genesis.go
- x/staking/simulation/operations.go
- add x/staking module with min_commision_rate parameter
- add ante handler to check validator create/update TXs for min commission value
refs akash-network/support#73
> feat: implement check for min validator commission

- app/ante.go
- app/app.go
- app/app_configure.go
- app/decorators/gov_filter.go
- x/gov/alias.go
- x/gov/genesis.go
- x/gov/keeper/keeper.go
- x/gov/module.go
- x/gov/simulation/genesis.go
- x/gov/simulation/operations.go
- add x/gov module with initial deposit rate parameter
- add ante handler to filter proposals if the initial deposit is less than min_deposit*min_initial_deposit_rate
refs akash-network/support#73
> feat: filter gov proposals by initial deposit

- go.mod
- go.sum
> fix: bump ibc-go to v3.4.0

- app/upgrades.go
- app/upgrades/v0.22.0/upgrade.go
> feat: network upgrade v0.22.0

- sdl/resources.go
> fix: default GPU resource to 0 if not present

- sdl/v2_test.go
> fix(sdl/test): add missing GPU resources

- .github/workflows/sims.yaml
> ci(sims): remove MAINNET var

- Makefile
> refactor(build): remove static_build tag

- .github/workflows/sims.yaml
> ci(sims): do not unshallow repo on sims

- cmd/akash/cmd/bech32.go
- cmd/akash/cmd/root.go
> feat: add bech32-convert command to easily convert address prefixes

- .github/workflows/release-dry-run.yaml
> ci(release): fetch latest tag using rev-list

- util/cli/configs.go
> fix: suppress lint for config error

- .github/pr_labeler.yaml
> ci: extend pr labeler

- go.mod
- go.sum
> chore: bump akash-api v0.0.15

- testutil/base.go
> fix(testutil): default gpu units to 0

- go.mod
- go.sum
> chore: bump akash-api to v0.0.16

- util/cli/configs.go
> fix: bind all env prefixes to the flags

- .envrc
> chore: remove go check from direnv as this breaks gh actions

- Makefile
- make/init.mk
- make/setup-cache.mk
> feat(tools): install cosmovisor on demand

- go.mod
- go.sum
> chore: bump cosmos-sdk to v0.45.16

- make/init.mk
- make/mod.mk
- make/releasing.mk
- make/test-integration.mk
- make/test-upgrade.mk
> build(tests): make go mod configurable

- cmd/akash/cmd/testnetify/accounts.go
- cmd/akash/cmd/testnetify/cmd.go
- cmd/akash/cmd/testnetify/state.go
- cmd/akash/cmd/testnetify/validators.go
- meta.json
> fix(testnetify): fix token balance flow in testnetify genesis

- sdl/gpu.go
- sdl/gpu_test.go
- sdl/resources.go
prevents temporary data to be included in manifest version
Closes: #XXXX
---
I have...
> fix(sdl): use GPU custom attribute types in place

- go.mod
- go.sum
> chore: bump akash-api to v0.0.22

- .github/pr_labeler.yaml
> ci(labeler): add labels for x/take and upgrades

- upgrades/types/types.go
> fix(take): add default consensus version for take module

- upgrades/software/v0.24.0/upgrade.go
> fix(upgrades): error if feegrant module is not initialized

- README.md
> docs(readme): remove simulations badge. they are part of tests group

- Makefile
- cgo_trace.go
- go.mod
- go.sum
allows debugging Ledger
refs akash-network/support#23
> feat: add cgosymbolizer to traceback C

- upgrades/CHANGELOG.md
> docs: add changelog for network upgrades

- _docs/adr/adr-002-manifest-v2beta2.md
> docs(adr): ADR 002 Manifest v2beta2

- upgrades/software/v0.24.0/upgrade.go
> fix(upgrade): use custom commission validator during v0.24.0 upgrade

- sdl/_testdata/simple3.yaml
- sdl/expose.go
- sdl/v2_test.go
> fix(sdl): ensure service expose is sorted

- make/test-upgrade.mk
> chore(build): remove double make from test upgrade

- make/test-integration.mk
> refactor(build): remove mocks from modules under test

- go.mod
- go.sum
- x/deployment/simulation/genesis.go
- x/take/keeper/keeper.go
- x/take/module.go
> refactor(v1beta3): convert params from map to slice

- go.mod
- go.sum
> chore: bump ibc-go to v4.4.2

- sdl/expose.go
> fix(sdl): remove check if expose is global when building

- testutil/network/network.go
- testutil/network/util.go
- testutil/network_suite.go
- testutil/types.go
- x/cert/client/cli/grpc_rest_test.go
- x/deployment/client/cli/cli_test.go
- x/deployment/client/cli/grpc_rest_test.go
- x/market/client/cli/cli_test.go
- x/market/client/cli/grpc_rest_test.go
- x/provider/client/cli/cli_test.go
- x/provider/client/cli/grpc_rest_test.go
> feat(testutil): implement custom testnet config

- upgrades/software/v0.24.0/upgrade.go
> chore(upgrade): tidy up errors formatting

- x/market/client/cli/cli_test.go
> chore(market): remove redundant sprintf

- upgrades/CHANGELOG.md
> docs(upgrade): backport descriptions for past network upgrades

- go.mod
- go.sum
- make/test-upgrade.mk
- tests/upgrade/upgrade_test.go
- testutil/state/suite.go
- x/take/keeper/keeper.go
> fix(x/take): set 2 percent AKT take rate during v0.24.0 upgrade

- sdl/_testdata/simple4.yaml
- sdl/_testdata/v2.1-deployment-svc-mismatch.yaml
- sdl/_testdata/v2.1-private_service.yaml
- sdl/_testdata/v2.1-profile-svc-name-mismatch.yaml
- sdl/_testdata/v2.1-service-mix.yaml
- sdl/_testdata/v2.1-service-mix2.yaml
- sdl/_testdata/v2.1-simple-gpu.yaml
- sdl/_testdata/v2.1-simple-with-ip.yaml
- sdl/_testdata/v2.1-simple.yaml
- sdl/_testdata/v2.1-simple2.yaml
- sdl/_testdata/v2.1-simple3.yaml
- sdl/_testdata/v2.1-simple4.yaml
- sdl/groupBuilder_v2.go
- sdl/groupBuilder_v2_1.go
- sdl/sdl.go
- sdl/v2_1.go
- sdl/v2_1_ip_test.go
- sdl/v2_1_test.go
- x/deployment/testdata/deployment-v2.1-ip-endpoint.yaml
- x/deployment/testdata/deployment-v2.1-multi-groups-ip-endpoint.yaml
- x/deployment/testdata/deployment-v2.1-multi-ip-endpoint.yaml
- x/deployment/testdata/deployment-v2.1-shared-ip-endpoint.yaml
- x/deployment/testdata/deployment-v2.1.yaml
> feat: sdl v2.1

- cmd/akash/cmd/root.go
- util/server/server.go
> feat: export genesis to custom file

- README.md
Updates README with the correct go version
---
I have...
> docs(readme): set golang version to 1.21.0

- install.sh
> feat(install): customize os and arch during install

- pubsub/bus.go
> feat(pubsub): implement publisher interface

- make/releasing.mk
> fix(build): switch goreleaser to use clean

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- make/test-upgrade.mk
- script/upgrades.sh
- tests/upgrade/config.json
- tests/upgrade/test-config.json
- tests/upgrade/types/types.go
- tests/upgrade/upgrade-v0.26.0.json
- tests/upgrade/upgrade_test.go
> feat(tests): run multiple validators within upgrade test

- sdl/_testdata/storageClass6.yaml
- sdl/v2_test.go
> feat(sdl): test volumes named correctly within deployment group

- README.md
> docs(readme): fix validator page link

- tests/upgrade/upgrade_test.go
> chore(tests): wait a block period prior quering for upgrade proposal

- tests/upgrade/upgrade_test.go
> fix(tests): set fixed gas for upgrade test

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- Makefile
- make/init.mk
- make/test-upgrade.mk
- script/upgrades.sh
- tests/upgrade/upgrade_test.go
> test(upgrade): return upgrade version to test against

- meta.json
> chore: bump from binary for upgrade v0.28.0

- go.mod
- go.sum
> chore(deps): bump akash-api to v0.0.36

- script/tools.sh
> chore(scripts): remove execution dump from tools.sh

- go.mod
- go.sum
- x/audit/client/cli/tx.go
- x/cert/client/cli/tx.go
- x/deployment/client/cli/tx.go
- x/market/client/cli/tx.go
- x/provider/client/cli/tx.go
> chore: bump akash-api

- go.mod
- go.sum
> chore(ledger): fixes error during ledger sign on latest cosmos app

- x/cert/client/cli/tx.go
> fix(x/cert): skip client discovery if gentx is in place

- go.mod
- go.sum
> fix: bump akash-api. fixes fees option

- go.mod
- go.sum
- x/deployment/handler/handler_test.go
> chore: bump api to v0.0.58. changes default deposits

- .github/workflows/concommits.yaml
- .github/workflows/labeler.yaml
- .github/workflows/release.yaml
- .github/workflows/standardize-yaml.yaml
- .github/workflows/tests.yaml
- .github/workflows/wip.yaml
> ci: bump actions

- go.mod
- go.sum
> chore(mod): bump akash api

- .goreleaser.yaml
> chore(goreleaser): fix typo

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: fix typo

- testutil/network/network.go
> fix(testutil): allocate all ports for testnet validator at once

- go.mod
> fix: retract v0.34.0 release
